<table class="table-dashed mgl10">
	<?php foreach ($this->sorts as $i => $s): ?>
	<tr>
		<td class="mgl10">
			<?php if(isset($this->default[$i])): ?>
				<input class="item" type="text" value="<?= $s ?>" disabled="disabled" />
			<?php else: ?>
				<input id="s_<?= $i ?>" class="item" type="text" value="<?= $s ?>"  />
				<input id="btn_<?= $i ?>" onclick="save_sort(<?= $i ?>)" type="button" class="btn" value="保存" />
				<input id="del_<?= $i ?>" onclick="del_sort(<?= $i ?>)" type="button" class="btn" value="删除" />
			<?php endif; ?>
		</td>
	</tr>
	<?php endforeach; ?>
	<tr>
		<td class="mgl10">
			<input type="text" id="new_item" value=""  />
			<input onclick="create_sort()" type="button" id="create_btn" class="btn" value="添加" />
		</td>
	</tr>
</table>

<script type="text/javascript">
	function del_sort(sid)
	{
		var c = confirm('确定删除该分组？删除后该分组下的好友需要重新分组');
		if(c == true)
		{
			$('#del_'+sid).val('删除中..').attr('disabled', true);
			$.post('/space_friends/sort/del', {sid:sid}, function(data){
				if(data == 'success') history.go(0);
				else{ alert(data); $('#del_'+sid).val('删除').attr('disabled', false); }
			});	
		}
	}

	function save_sort(sid)
	{
		var val = $('#s_'+sid).val();
		$('#btn_'+sid).val('保存中..').attr('disabled', true);
		$.post('/space_friends/sort/save', {sid:sid,val:val}, function(data){
			if(data == 'success') $('#btn_'+sid).val('保存成功').attr('disabled', false);
			else{ alert(data); $('#btn_'+sid).val('保存').attr('disabled', false); }
		});
	}
	
	function create_sort()
	{
		var len = $('.item').length;
		var val = $('#new_item').val();
		$('#create_btn').val('添加中..').attr('disabled', true);
		$.post('/space_friends/sort/create', {sid:(len+1),val:val}, function(data){
			if(data == 'success') history.go(0);
			else{ alert(data); $('#create_btn').val('添加').attr('disabled', false); }
		});
	}
</script>