<form id="apoint_form" method="post" onsubmit="return apoint()">
	<table width="90%" class="mg10">
		<tr>
			<td class="txtr">为谁申请：</td>
			<td>
				<div id="ps_box" class="pd5 quiet">输入想要申请人的姓名，多个姓名请用英文半角空格分隔</div>
				<input onkeypress="ref_list()" name="uname" id="uname_box" type="text" value="" size="70" /> 
				<a href="javascript:myself()">为自己</a>
			</td>
		</tr>
		<tr>
			<td class="txtr">申请分值：</td>
			<td>
				<input name="point" type="text" value="" size="10" /> 
				<span class="quiet">分值不能高于10分</span>
			</td>
		</tr>
		<tr>
			<td class="txtr">缘由：</td>
			<td>
				<textarea name="memo" style="width:380px; height:200px"></textarea>
			</td>
		</tr>
		<tr>
			<td colspan="2" class="txtc">
				<input class="btn" type="submit" value="确定申请" />
			</td>
		</tr>
	</table>
	<input id="checkflag" type="hidden" value="0" />
	<input id="incepter" type="hidden" name="auid" value="<?= $_GET['uid'] ?>" />
</form>
	
<script type="text/javascript">
	var t = 0;
	function apoint(){
		$('input:submit').val('发送中..').attr('disabled', true);
		$.post('/public/point/award',
			   $('#apoint_form').serializeArray(),
			   function(data){
			if(data != 'done'){ alert(data); $('input:submit').val('重新申请').attr('disabled', false); }
			else { $('input:submit').val('申请成功'); location.href='/public/point/?tab=alog'; }
		});
		return false;
	}
	function ref_list()
	{
		t = 0;
		setTimeout('show_names()', 500);
	}
	function show_names()
	{
		var v = $('#uname_box').val();
		if(t == 0)
		{
			t++;
			$('#ps_box').load('/public/point/forwho', {uname:v});
		}
	}
	function myself(){
		$('#incepter').val(<?= Cmd::uid(); ?>);
		$('#uname_box').val('<?= Cmd::getSess('profile', 'username') ?>');
	}
</script>