<div class="yui-main">
	<h3 class="section-u">
		<img src="<?= Alp_Url::img('icon/1616/box.gif'); ?>" class="vm mgr10" />最新动态
	</h3>
	<table class="table-dashed" width="100%">
	<?php if(count($this->log) > 0): foreach($this->log as $r): ?>
	<tr>
		<td width="18">
			<img src="<?= Alp_Url::img('icon/log/'.$r['key'].'.gif'); ?>" />
		</td>
		<td>
			<a href="/space_home/?uid=<?= $r['uid'] ?>"><?= $r['uname'] ?></a>
			<?= ((int)$r['fid'] > 0) ? ' 将 <a href="/space_home/?uid='.$r['fid'].'">'.$r['fname'].'</a>':'' ?>
			<?= $this->event[$r['key']] ?>
			<?php if($r['tid'] > 0): ?>
			<a href="/space_bar/<?= $r['type'] ?>/view?tid=<?= $r['tid'] ?>"><?= $r['title'] ?></a>
			<?php endif; ?>
		</td>
		<td width="30%" class="quiet txtr" valign="top"><?= Alp_Date::normal($r['time']) ?></td>
	</tr>
	<?php endforeach; else: ?>
	<tr>
		<td class="quiet">尚未跟您有关的信息动态</td>
	</tr>
	<?php endif; ?>
	</table>
</div>