<div class="yui-g">
	<div class="yui-u first" style="width:20%;">
		<div class="head80">
			<img style="margin:20px 0 0 20px" src="<?= Cmd::userhead(Cmd::uid(), '80', Cmd::getSess('profile','sex')) ?>" />
		</div>
		<div class="a-span" style="line-height:150%">
			<a href="/space_set/detail/">详细资料</a>
			<a href="/space_set/profile/head">更换头像</a>
			<br />
			<a href="/space_set/profile">更新资料</a>
			<a href="/space_set/privacy">隐私设置</a>
			<br />
			<!-- <a style="color:#BD4C00" href="/space_home/ext/bar">我的话题</a> -->
		</div>
		<br /><br />
	</div>
	<div class="yui-u mgt10" style="width:79%;">
		<b class="f14"><?= $this->profile['username'] ?></b>
		<span class="ing mgl10">
		<a href="javascript:ing()" style="color:#666"><span id="iamdoing"></span>
			<img src="<?= Alp_Url::img('icon/mix/tool.gif') ?>" />
		</a>
		</span>
		<span class="ing hide mgl10">
			<input id="ing_put" type="text" name="ing" value="" />
			<a href="javascript:doing()"><img src="<?= Alp_Url::img('icon/mix/v.gif'); ?>" /> 确定</a>
			<a href="javascript:ing()"><img src="<?= Alp_Url::img('icon/mix/x.gif'); ?>" /> 取消</a>
		</span>
		<hr />
		<table class="table-dashed" width="100%">
		<?php foreach($this->home as $v): 
		$str = Logic_Space_Home::info($v, Cmd::uid()) ?>
		<?php if($str): ?>
		<?php if($v == 'intro'): ?>
		<tr>
			<td class="txtr"><b>个人介绍：</b></td>
			<td><a id="intro_slide" href="javascript:slide('intro')">展开</a></td>
		</tr>
		<?php endif; ?>
		<?php if($v == 'contact'): ?>
		<tr>
			<td class="txtr"><b>联系方式：</b></td>
			<td><a id="contact_slide" href="javascript:slide('contact')">展开</a></td>
		</tr>
		<?php endif; ?>
		<?php if($v == 'career'): ?>
		<tr>
			<td class="txtr"><b>工作情况：</b></td>
			<td><a id="career_slide" href="javascript:slide('career')">展开</a></td>
		</tr>
		<?php endif; ?>
		<?= $str ?>
		<?php endif; endforeach; ?>
		</table>
	</div>
</div>

<script type="text/javascript">
	
	function getdoing()
	{
		$.get(
			'/space_home/index/getdoing?uid=<?= Cmd::uid() ?>',
			null,
			function(data)
			{ 
				$('#iamdoing').text(data);
				$('#ing_put').val(data); 
			}
		);
	}
	
	function doing()
	{
		$.post(
			'/space_home/my/doing',
			$('#ing_put').serializeArray(),
			function(data)
			{
				//alert(data);
				ing();
				getdoing();
			}
		);
	}
	
	function ing()
	{
		$('.ing').toggle();
		$('#ing_put').focus().select();
	}

	function slide(p)
	{
		if($('#'+p+'_slide').text() == '展开'){
			$('.'+p).show(); $('#'+p+'_slide').text('折起');
		} else {
			$('.'+p).hide(); $('#'+p+'_slide').text('展开');
		}
	}
	getdoing();
</script>