<div class="yui-main">
	<div class="yui-b">
		<div class="mg5 section yui-g">
			<div class="yui-u first">
				<img class="vm mgr10" src="<?= Alp_Url::img('icon/1616/group.gif') ?>" /><b>群组俱乐部</b>
			</div>
			<div class="yui-u txtr"><a href="javascript:history.back()">返回上一页</a></div>
		</div>
		<?= $this->action('tab', 'index', 'space_group', array('list'=>$this->list)); ?>
		<?= $this->action($this->list, 'index', 'space_group'); ?>
	</div>
</div>
<?= $this->render('index/sidebar.phtml'); ?>