<div class="yui-g mglr10">
	<div class="yui-u first" style="width:75%">
		<div class="tb-box">
			<a href="/space_group/?list=my" <?= ($this->list == 'my')?'class="tb-on"':'class="tb-of"' ?>>我的群</a><span class="tb-rbg"></span>
			<a href="/space_group/?list=friend" <?= ($this->list == 'friend')?'class="tb-on"':'class="tb-of"' ?>>好友的群</a><span class="tb-rbg"></span>
			<a href="/space_group/?list=all" <?= ($this->list == 'all')?'class="tb-on"':'class="tb-of"' ?>>所有群</a><span class="tb-rbg"></span>
		</div>
	</div>
	<div class="yui-u txtr a-span" style="width:25%">
		<a href="/space_group/pub">
			<img class="vm" src="<?= Alp_Url::img('icon/mix/+.gif') ?>" /> 创建新群</a>
		<a href="/space_search/group">
			<img class="vm" src="<?= Alp_Url::img('icon/mix/search.gif') ?>" /> 搜索</a>
	</div>
</div>