<div class="yui-g mglr10">
	<div class="yui-u first" style="width:85%">
		<div class="tb-box">
			<a href="?type=list" <?= ($this->type == 'list')?'class="tb-on"':'class="tb-of"' ?>>我的好友</a><span class="tb-rbg"></span>
			<a href="?type=sort" <?= ($this->type == 'sort')?'class="tb-on"':'class="tb-of"' ?>>分组管理</a><span class="tb-rbg"></span>
			<a href="?type=visit" <?= ($this->type == 'visit')?'class="tb-on"':'class="tb-of"' ?>>最近来访</a><span class="tb-rbg"></span>
			<a style="color:#6C950F" href="?type=invite" <?= ($this->type == 'invite')?'class="tb-on"':'class="tb-of"' ?>>邀请注册</a><span class="tb-rbg"></span>
		</div>
	</div>
	<div class="yui-u txtr a-span" style="width:15%">
		<a href="/space_search/?for=user&range=friend">
			<img class="vm" src="<?= Alp_Url::img('icon/mix/search.gif') ?>" /> 搜索</a>
	</div>
</div>