<?php if($this->comments): ?>
	<div class="pg"><?= $this->pagination ?></div>
<?php foreach ($this->comments as $i => $r): ?>
<table width="100%">
  <tr>
    <td rowspan="2" width="8%" valign="top">
    	<div class="head40 txtc">
			<?php if($r['nicky']): ?>
				<img class="mg10" src="<?= Cmd::userhead(0,40,$r['usex']) ?>" />
			<?php else: ?>
			<a href="/space_home/?uid=<?= $r['uid'] ?>">
				<img class="mg10" src="<?= Cmd::userhead($r['uid'],40,$r['usex']) ?>" />
			</a>
			<?php endif; ?>
		</div>
    </td>
    <td class="yui-g section-sub quiet" width="92%">
    	<div id="quote_<?= $r['id'] ?>" class="yui-u first" style="width:75%">
    		<img class="online_state" src="<?= Alp_Url::img('icon/1616/offline.gif') ?>" rel="<?= $r['uid'] ?>" />
			<?php if($r['nicky']): ?>
			<?= $r['unick'] ?>
			<?php else: ?>
			<a href="/space_home/?uid=<?= $r['uid'] ?>"><?= $r['uname'] ?></a>
			<?php if($r['honor']): ?>
				<span class="quiet">[<?= $r['honor'] ?>]</span>
			<?php endif; ?>
			<?php endif; ?>说道：
		</div>
		<div class="yui-u txtr" style="width:25%">
			<?= date('y-m-d H:i:s', $r['time']) ?>
			&nbsp;&nbsp;&nbsp;&nbsp;
			<?= ($i+2)+($this->offset) ?>楼
			&nbsp;
			<a href="javascript:scroll(0,0)">top</a>
		</div>
    </td>
  </tr>
  <tr>
  	<td>
  		<div id="comment_<?= $r['id'] ?>" style="line-height:150%; font-size:13px; color:#333">
  			<?= ($r['deny'] == 0) ? stripslashes($r['content']) : '<div class="quiet">****该回帖已被屏蔽****</div>'; ?>
		</div>
		<?php if($r['sign']): ?>
  			<div class="pd10">
  				<img src="<?php echo Alp_Url::img('v1/sigline.gif')?>" />
  				<div class="quiet f12 pd5"><?php echo Cmd::b2h(stripslashes($r['sign'])) ?></div>
  			</div>
  		<?php endif; ?>
		<?= $this->action('toolbar', 'comment', 'space_bar', array('uid'=>$r['uid'],'cid'=>$r['id'])); ?>
  	</td>
  </tr>
</table>
<?php endforeach; ?>
	<div class="pg"><?= $this->pagination ?></div>
<?php else: ?>
<p class="f12 quiet" style="padding-left:20px">尚未有人回帖，可以抢占沙发哦!</p>
<?php endif; ?>
<script>online_state();</script>