<div class="txtr a-span">
<?php if($this->role == 'master'): ?>
<a href="javascript:deny_comment(<?= $this->cid ?>)"><img src="<?= Alp_Url::img('icon/mix/lock.gif'); ?>" />屏蔽</a>
<a href="javascript:edit_comment(<?= $this->cid ?>)"><img src="<?= Alp_Url::img('icon/mix/edit.gif'); ?>" />修改</a>
<?php elseif($this->owner == Cmd::uid()): ?>
<a href="javascript:edit_comment(<?= $this->cid ?>)"><img src="<?= Alp_Url::img('icon/mix/edit.gif'); ?>" />修改</a>
<?php endif; ?>
</div>