<div class="yui-main">
	<div class="yui-b">
		<div class="mg5 section yui-g">
			<div class="yui-u first" style="width:80%">
				<img class="vm mgr10" src="<?= Alp_Url::img('icon/1616/smile.gif') ?>" /><b>校友互助</b>
				 :: 互助互利团结起来共建设美丽杭州
			</div>
			<div class="yui-u txtr" style="width:20%"><a href="javascript:history.back()">返回上一页</a></div>
		</div>
		<?= $this->render('tab.phtml'); ?>
		<hr class="dashed" />
	</div>
</div>