<?php $this->headTitle(htmlspecialchars(stripcslashes($this->row['title']))); ?>
<div class="yui-main">
	<div class="mg5 section yui-g">
		<div class="yui-u first" style="width:80%">
			<img class="vm mgr10" src="<?= Alp_Url::img('icon/1616/talk.gif') ?>" /><b>校友互助</b> 
			:: <a href="/space_bar/?type=help&sort=<?= $this->row['sort'] ?>"><?= $this->row['sortname'] ?></a> / <?= stripcslashes($this->row['title']) ?>
		</div>
		<div class="yui-u txtr a-span" style="width:20%">
			<a href="javascript:history.back()">返回上一页</a>
			<?php if(!$this->row['group']): ?>
			<a href="/space_bar/">返回话题列表</a>
			<?php else: ?>
			<a href="/space_group/topic/?id=<?= $this->row['group'] ?>">返回群组帖区</a>
			<?php endif; ?>
		</div>
	</div>
	<table width="100%">
		<tr>
			<td rowspan="2" width="15%" valign="top" class="txtc">
				<div class="head80">
					<?php if($this->row['nicky']): ?>
					<img class="mg10 pd10" src="<?= Cmd::userhead(0,80,Cmd::getSess('profile','sex')) ?>" />
					<img class="online_state" src="<?= Alp_Url::img('icon/1616/offline.gif') ?>" rel="<?= $this->row['puber'] ?>" />
					<?= $this->row['unick'] ?>
					<?php else: ?>
					<a href="/space_home/?uid=<?= $this->row['puber'] ?>">
					<img class="mg10 pd10" src="<?= Cmd::userhead($this->row['puber'],80) ?>" />
					</a>
					<img class="online_state" src="<?= Alp_Url::img('icon/1616/offline.gif') ?>" rel="<?= $this->row['puber'] ?>" />
					<a href="/space_home/?uid=<?= $this->row['puber'] ?>"><?= $this->row['uname'] ?></a>
					<?php endif; ?>
				</div>
				<br /><br /><br />
			</td>
		</tr>
		<tr>
			<td width="85%">
				<div class="yui-g section-sub">
					<div class="yui-u first" style="width:80%">
						<b class="f14">
						【<span id="state_t" class="tp0"><?= ($this->row['state'] == 0) ? '待解决' : '已解决';  ?></span>】
						<?= stripcslashes($this->row['title']) ?></b>
					</div>
					<div class="yui-u txtr" style="width:20%">
						<?= Alp_Date::normal($this->row['pubtime']) ?> 
						&nbsp;&nbsp;&nbsp;&nbsp;
						楼主
					</div>
				</div>
				<div class="f14 pd10" style="line-height:150%;">
					<?= stripslashes($this->row['content']); ?>
						<?php if($this->row['memo']): ?>
						<b>互助补充：</b>
						<div class="memo">
							<?= stripslashes($this->row['memo']); ?>
						</div>
						<?php endif; ?>
					<span id="state_box" rel=<?= $this->row['state'] ?>></span>
				</div>
				<?= $this->render('toolbar.phtml'); ?>
			</td>
		</tr>
	</table>
	<?= $this->action('view', 'comment', 'space_bar') ?>
</div>
<script type="text/javascript">
<?php if($this->row['puber'] == Cmd::uid()): ?>
	function memo(){ var data = $('#memo_v').val(); $.post('/space_bar/help/memo?tid=<?= $this->row['tid'] ?>', {'data':data}, function(){ history.go(0); }); }
	function load_statebox(){ var state = $('#state_box').attr('rel'); $('#state_box').load('/space_bar/help/statebox?tid=<?= $this->row['tid'] ?>&state='+state, function(){ if(state == 0) $('#state_t').text('待解决');else $('#state_t').text('已解决'); }); }
	load_statebox();
	if($('.memo').length == 0){$('#state_box').before('<div class="memo">点击此处添加互助备注</div>');}
	$('.memo').one('click', function(){ var h = $(this).text(); h = h.replace(/(^\s*)|(\s*$)/g, ""); if(h == '点击此处添加互助备注') h = ''; $(this).html('<textarea id="memo_v" style="width:99%;height:80px">'+h+'</textarea><p class="txtr mg5"><input onclick="memo()" type="button" class="btn" value="保存" /></p>'); }).mouseover(function(){$(this).css('background','#ffc');}).mouseout(function(){$(this).css('background','#fff')});
<?php endif; ?>
</script>
