<div class="yui-main">
	<div class="yui-b">
		<div class="mg5 section yui-g">
			<div class="yui-u first" style="width:80%">
				<img class="vm mgr10" src="<?= Alp_Url::img('icon/1616/box.gif') ?>" />
				<b>杂项管理</b>
			</div>
			<div class="yui-u txtr" style="width:20%"><a href="javascript:history.back()">返回上一页</a></div>
		</div>
		<div class="tb-box">
			<a href="/console/mix/?tab=player" <?= ($this->tab == 'player')?'class="tb-on"':'class="tb-of"' ?>>展图</a><span class="tb-rbg"></span>
			<a href="/console/mix/?tab=ftpage" <?= ($this->tab == 'ftpage')?'class="tb-on"':'class="tb-of"' ?>>头版</a><span class="tb-rbg"></span>
			<a href="/console/mix/?tab=sysfile" <?= ($this->tab == 'sysfile')?'class="tb-on"':'class="tb-of"' ?>>文件</a><span class="tb-rbg"></span>
			<a href="/console/mix/?tab=links" <?= ($this->tab == 'links')?'class="tb-on"':'class="tb-of"' ?>>链接</a><span class="tb-rbg"></span>
		</div>
		<?= $this->action($this->tab, 'mix', 'console'); ?>
		</div>
</div>
<?= $this->render('sidebar.phtml') ?>