<div class="mg10 memo">
举例：<br />
	<?= htmlspecialchars('
		<?xml version="1.0" encoding="utf-8"?>
		<bcaster autoPlayTime="3">
		<item item_url="图片地址" link="打开链接" itemtitle="文字说明">
		</item>
		</bcaster>'
	); ?>
</div>
<form class="mg10" method="post">
	<textarea name="xml" style="width:625px;height:200px;background:#ffc"><?= $this->xml; ?></textarea>
	<div class="pd10 txtc"><input type="submit" value="保存修改" class="btn"></div>
</form>
