<?php 

	$alias = array(
		'login' => '登录签到加分',
		'pubevents' => '发起活动并给成员增加热心度'
	);

?>
<table class="pd5">
	<tr>
		<td><img src="<?= Alp_Url::img('v1/degup.jpg') ?>" /></td>
		<td>
			<h2 style="color:#D44848">恭喜，您的热心度增加了^_^</h2>
			<ul class="f14 quiet">
			<?php foreach ($this->params as $key => $pt): if(isset($alias[$key])): ?>
			<li><?= $alias[$key] ?>增加 <b style="color:#D44848"><?= $pt ?>pt</b></li>
			<?php endif; endforeach; ?>
			</ul>
		</td>
	</tr>
</table>