<div class="yui-main">
	<div class="yui-b">
		<div class="mg5 section yui-g">
			<div class="yui-u first">
				<img class="vm mgr10" src="<?= Alp_Url::img('icon/1616/profile.gif') ?>" /><b>账号信息设置</b>
			</div>
			<div class="yui-u txtr"><a href="javascript:history.back()">返回上一页</a></div>
		</div>
		<div class="mglr10 tb-box">
			<a href="/space_set/profile/base" <?= ($this->controller_name == 'profile')?'class="tb-on"':'class="tb-of"' ?>>个人资料</a><span class="tb-rbg"></span>
			<a href="/space_set/password/" <?= ($this->controller_name == 'password')?'class="tb-on"':'class="tb-of"' ?>>修改密码</a><span class="tb-rbg"></span>
			<a href="/space_set/privacy/" <?= ($this->controller_name == 'privacy')?'class="tb-on"':'class="tb-of"' ?>>隐私设置</a><span class="tb-rbg"></span>
		</div>
