<?php $this->headTitle(htmlspecialchars(stripcslashes($this->row['title']))); ?>
<div class="yui-main">
	<div class="mg5 section yui-g">
		<div class="yui-u first" style="width:70%">
			<img class="vm mgr10" src="<?= Alp_Url::img('icon/1616/talk.gif') ?>" /><b>新闻资讯</b> 
			:: <a href="/public/news/?sort=<?= $this->row['sort'] ?>"><?= $this->row['sortname'] ?></a> / <?= stripcslashes($this->row['title']) ?>
		</div>
		<div class="yui-u txtr a-span" style="width:30%">
			<a href="javascript:history.back()">返回上一页</a>
			<a href="/public/news/">返回新闻资讯主页</a>
		</div>
	</div>
	<?= $this->action('prenext', 'news', 'public', array('id' => $this->row['tid'])); ?>
	<table width="100%">
		<tr>
			<td>
				<div class="yui-g section-sub">
					<div class="yui-u first" style="width:80%">
						<img class="online_state" src="<?= Alp_Url::img('icon/1616/offline.gif') ?>" rel="<?= $this->row['puber'] ?>" />
						<?php if($this->row['nicky']): ?>
						<?= $this->row['unick'] ?>
						<?php else: ?>
						<a href="/space_home/?uid=<?= $this->row['puber'] ?>"><?= $this->row['uname'] ?></a>
						<?php endif; ?>：
						<b class="f14"><?= stripcslashes($this->row['title']) ?></b>
					</div>
					<div class="yui-u txtr" style="width:20%">
						<?= Alp_Date::normal($this->row['pubtime']) ?> 
					</div>
				</div>
				<div class="f14 pd10" style="line-height:150%;">
					<?= stripslashes($this->row['content']); ?>
				</div>
			</td>
		</tr>
	</table>
	<hr class="dashed" />
	<br />
	<?= $this->action('prenext', 'news', 'public', array('id' => $this->row['tid'])); ?>
	<br />
	<div class="notice f14 a-span">
		只有注册校友才能对新闻进行回复评论。
		<a href="/space_bar/news/view?tid=<?= $this->row['tid'] ?>">立即登录</a>
		<a href="/public/reg/">注册帐号</a>
	</div>
</div>