<?php // black
if(Cmd::role() != 'black'): ?>
<div class="mods yui-g f14 a-span">
	<div class="yui-u first">
		<img src="<?= Alp_Url::img('icon/1616/talk.gif') ?>" /><a href="/space_bar/">公共帖吧</a>
	</div>
	<div class="yui-u">
		<img src="<?= Alp_Url::img('icon/1616/news.gif') ?>" /><a href="/space_bar/?type=news">新闻快递</a>
	</div>
	<div class="yui-u first">
		<img src="<?= Alp_Url::img('icon/1616/tea.gif') ?>" /><a href="/space_bar/?type=events">校友活动</a>
	</div>
	<div class="yui-u">
		<img src="<?= Alp_Url::img('icon/1616/smile.gif') ?>" /><a href="/space_bar/?type=help">校友互助</a>
	</div>
	<div class="yui-u first">
		<img src="<?= Alp_Url::img('icon/1616/vote.gif') ?>" /><a href="/space_bar/?type=vote">投票调查</a>
	</div>
	<div class="yui-u">
		<img src="<?= Alp_Url::img('icon/1616/pic.gif') ?>" /><a href="/space_bar/?type=photo">看图论事</a>
	</div>
	<div class="yui-u first">
		<img src="<?= Alp_Url::img('icon/1616/share.gif') ?>" /><a href="/space_bar/?type=share">文件共享</a>
	</div>
	<div class="yui-u">
		<img src="<?= Alp_Url::img('icon/1616/video.gif') ?>" /><a href="/space_bar/?type=video">视频共赏</a>
	</div>
</div>

<hr class="dashed" />
<div class="mods yui-g f14 a-span">
	<div class="yui-u first">
		<img src="<?= Alp_Url::img('icon/1616/group.gif') ?>" /><a href="/space_group/">群组俱乐部</a>
	</div>
	<div class="yui-u">
		<img src="<?= Alp_Url::img('icon/1616/search.gif') ?>" /><a href="/space_search/">资源搜索</a>
	</div>
</div>
<?php else: ?>
详细原因可来电咨询。<br />
电话：0571-8998 8185/8998 8186<br />
或者直接<a href="/space_msg/pm/?uid=1">PM管理员</a>
<?php endif; ?>

<?php // member
if(Cmd::role() != 'black' && Cmd::role() != 'bench'):  ?>

<?php endif; ?>
	
<?php // power
if(Cmd::role() == 'power'): ?>

<?php endif; ?>
	
<?php // master
if(Cmd::role() == 'master'): ?>
<hr class="dashed" />
<div class="mods yui-g f14 a-span">
	<div class="yui-u first">
		<img src="<?= Alp_Url::img('icon/1616/f_user.gif') ?>" /><a href="/console/user/">用户管理</a>
	</div>
	<div class="yui-u">
		<img src="<?= Alp_Url::img('icon/1616/f_doc.gif') ?>" /><a href="/console/bar/">帖子管理</a>
	</div>
	<div class="yui-u first">
		<img src="<?= Alp_Url::img('icon/1616/f_heart.gif') ?>" /><a href="/console/point/">热度管理</a>
	</div>
	<div class="yui-u">
		<img src="<?= Alp_Url::img('icon/1616/s_mail.gif') ?>" /><a href="/console/msg/">群发消息</a>
	</div>
	<div class="yui-u first">
		<img src="<?= Alp_Url::img('icon/1616/box.gif') ?>" /><a href="/console/mix/">杂项管理</a>
	</div>
	<div class="yui-u">
		
	</div>
</div>
<?php endif; ?>
<hr class="dashed" />
<div class="mods yui-g">
	<div class="yui-u f14 first a-span">
		<img src="<?= Alp_Url::img('icon/1616/friend.gif') ?>" /><a href="/space_friends/">我的好友</a>
	</div>
	<div class="yui-u f14 a-span">
		<img src="<?= Alp_Url::img('icon/1616/invite.gif') ?>" /><a class="f14" href="/space_friends/?type=invite">邀请注册</a>
	</div>
	<div class="yui-u f14 first a-span">
		<img src="<?= Alp_Url::img('icon/1616/rss.gif') ?>" /><a href="#/space_rss/">信息订阅</a>
	</div>
	<div class="yui-u">
		最近<a class="f14" href="/space_search/?for=user&range=online"><?= Logic_Api::onlinex() ?>人</a>在线
	</div>
</div>