<?php $r = $this->row; ?>
<a href="javascript:crole(<?= $r['uid'] ?>,'power')">
	<img src="<?= Alp_Url::img('icon/1616/arrow_up.gif') ?>" />
	成员
</a>
<a href="javascript:crole(<?= $r['uid'] ?>,'bench')">
	<img src="<?= Alp_Url::img('icon/1616/arrow_down.gif') ?>" />
	待审核
</a>
<a href="javascript:crole(<?= $r['uid'] ?>,'black')">
	<img src="<?= Alp_Url::img('icon/1616/arrow_bottom.gif') ?>" />
	冻结
</a>
<a href="javascript:initpsw(<?= $r['uid'] ?>)">初始密码</a>