<?= $this->render('header.phtml') ?>

<form id="password_form" method="post" class="mg10" onsubmit="return set_password()">
	<table class="table-dashed mg10" width="80%">
		<tr>
			<td width="20%" class="txtr">原密码：</td>
			<td><input type="password" name="opassword" /></td>
		</tr>
		<tr>
			<td class="txtr">新密码：</td>
			<td><input type="password" name="password" /></td>
		</tr>
		<tr>
			<td class="txtr">确认密码：</td>
			<td><input type="password" name="password2" /></td>
		</tr>
		<tr>
			<td></td>
			<td><input class="btn" id="submit" type="submit" value="修改密码" /></td>
		</tr>
	</table>
</form>

<script type="text/javascript">
	function set_password()
	{
		$('#submit').attr('disabled', true).val('修改密码中...');
		$.post(
			'/space_set/password/',
			$('#password_form').serializeArray(),
			function(data)
			{
				if(data == 'success')
				$('#submit').attr('disabled', false).val('密码修改成功，下次登陆将生效');
				else
				{
					alert(data);
					$('#submit').attr('disabled', false).val('修改密码');
				}
			}
		);	
		return false;
	}
</script>

<?= $this->render('sidebar.phtml') ?>