<div id="hd" class="yui-g">
	<div class="yui-u first" style="width:200px;"><a href=""><img src="<?= Logic_Addon_Partners::logo($this->corp['cid']) ?>" /></a></div>
	<div class="yui-u hd-r" style="width:730px;"><h1 class="f28"><?= $this->corp['name'] ?></h1></div>
</div>
<div id="bd">
	<a href="<?= $this->corp['website'] ?>"><img width="920" src="<?= Logic_Addon_Partners::banner($this->corp['cid'])?>" /></a>
	<div id="yui-main">
		<div class="yui-b">
			<div class="mgl10">
				<?= stripslashes($this->corp['intro']) ?>
			</div>
		</div>
	</div>
	<div class="yui-b">
		<table width="100%" style="border-left:1px dashed #ccc">
			<?php if($this->manager): ?>
			<tr>
				<td class="f14 section">
				<a href="/addon_partners/manage/corplist?uid=<?= $this->corp['uid'] ?>">返回企业列表</a>
				</td>
			</tr>
			<?php endif; ?>
			<tr>
				<td class="f12">联系人：<?= $this->corp['contact'] ?></td>
			</tr>
			<tr>
				<td class="f12">电话：<?= $this->corp['tel'] ?></td>
			</tr>
			<tr>
				<td class="f12">地址：<?= $this->corp['address'] ?></td>
			</tr>
			<tr>
				<td class="f12">网站：<a href="<?= $this->corp['website'] ?>" target="_blank"><?= $this->corp['website'] ?></a></td>
			</tr>
		</table>
	</div>
</div>

<div id="ft-l"></div>
<div id="ft-r"></div>

<script>
	$('#doc2').addClass('yui-t5');
</script>