<form id="login_form" class="mgl10" method="post" onsubmit="return login_form()">
    <table>
        <tr>
            <td><b class="f14">登录帐号</b></td>
            <td>
                <input size="30" type="text" name="account" value="<?php if($this->account) echo $this->account; elseif(!$this->relogin) $this->remember[0] ?>" maxlength="16" />
                <span class="valid_tip" id="account"></span>
            </td>
        </tr>
        <tr>
            <td><b class="f14">登录密码</b></td>
            <td>
                <input size="30" type="password" name="password" value="<?= ($this->relogin) ? '' : $this->remember[1] ?>" />
                <span class="valid_tip" id="password"></span>
            </td>
        </tr>
        <tr>
            <td>
            	<input type="hidden" name="rememberme" value="0" />
            	<input class="nob" name="rememberme" type="checkbox" id="rememberme" value="1" />
            	<label for="rememberme">下次自动登录</label>
            </td>
            <td>
                <input type="hidden" name="sid" value="<?= Zend_Session::getId() ?>" />
                <input id="submit" class="btn" type="submit" value="登录" />
                <span class="valid_tip" id="form_tip"></span>
            </td>
        </tr>
    </table>
</form>
<script type="text/javascript">
function login_form()
{
    $('.valid_tip').empty();
    $('#submit').val('登录中..').attr('disabled', true);
    $.post('/public/login/dologin', $('#login_form').serializeArray(), function(data){ alert(data) });
    /*
    $.getJSON(
        '/public/login/dologin',
        $('#login_form').serializeArray(),
        function(data){
        	if(data.form_tip != 'success')
        	{
        		$.each(data, function(name, value){
                    $('#'+name).html(value);
                });
        	}
            else{
        	<?php if($this->relogin): ?>
                if(data.goto == undefined)
                    history.go(0);
                else
                    location.href=data.goto;
        	<?php else: ?>
                if(data.goto == undefined)
                    location.href='/';
                else
                    location.href=data.goto;
            <?php endif; ?>
            }
            $('#submit').val('登录').attr('disabled', false);
        }
    );*/
    return false;
}
</script>