<form id="login_form" class="mgl10 niceform" method="post" onsubmit="return login_form()">
    <table>
        <tr>
            <td><b class="f14">登录帐号</b></td>
            <td>
                <input size="30" type="text" name="account" value="<?= ($this->account)?$this->account:($this->relogin)?'':$this->remember[0] ?>" maxlength="16" />
                <span class="valid_tip" id="account"></span>
            </td>
        </tr>
        <tr>
            <td><b class="f14">登录密码</b></td>
            <td>
                <input size="30" type="password" name="password" value="<?= ($this->relogin) ? '' : $this->remember[1] ?>" />
                <span class="valid_tip" id="password"></span>
            </td>
        </tr>
        <tr>
            <td>
            	<input type="hidden" name="rememberme" value="0" />
            	<input name="rememberme" type="checkbox" id="rememberme" value="1" />
            	<label for="rememberme">下次自动登录</label>
            </td>
            <td>
                <input type="hidden" name="sid" value="<?= Zend_Session::getId() ?>" />
                <input id="submit" type="submit" value="登录" />
                <span class="valid_tip" id="form_tip"></span>
            </td>
        </tr>
    </table>
</form>
<script type="text/javascript">
$(document).ready(function(){
	$.NiceJForms.build({
		imagesPath:"/cs/nicejform/images/default/"
	});
	<?php if($this->remember): ?>
	$('#rememberme').attr('checked', true);
	$('#submit').val('登陆中..');
	login_form();
	<?php endif; ?>
});
function login_form()
{
    $('.valid_tip').empty();
    $('#submit').val('登录中..').attr('disabled', true);
    $.getJSON(
        '/public/login/dologin',
        $('#login_form').serializeArray(),
        function(data){
        	if(data.form_tip != 'success')
        	{
        		$.each(data, function(name, value){
                    $('#'+name).html(value);
                });
        	}
        	<?php if($this->relogin): ?>
        	else history.go(0);
        	<?php else: ?>
            else location.href='/';
            <?php endif; ?>
            $('#submit').val('登录').attr('disabled', false);
        }
    );
    return false;
}
</script>