<table width="100%" class="table-dashed">
<tr class="bcolor-z">
	<td class="a-span">
	<a href="javascript:notsartyet()">近期活动</a>
	<a href="javascript:recentend()">刚结束的</a>
	</td>
	<td class="txtr"><a href="/space_bar/?type=events">&gt;&gt;更多</a></td>
</tr>
<?php if(count($this->events) > 0):  ?>
<?php foreach ($this->events as $i => $e): ?>
<tr class="nostart_events">
	<td>
		<img src="<?= Alp_Url::img('icon/num/v'.($i+1).'.gif') ?>" />
		<a href="/space_bar/events/view?tid=<?= $e['tid'] ?>">
			<?= stripcslashes($e['title']) ?>
		</a>
	</td>
	<td class="f9 quiet txtr" width="80" valign="top">
		<?= date('y/m/d H:i', $e['starttime']) ?>
	</td>
</tr>
<?php endforeach; ?>
<?php else: ?>
<tr class="nostart_events">
	<td colspan="2">
		没有记录
	</td>
</tr>
<?php endif; ?>

<?php if(count($this->events_recent) > 0):  ?>
<?php foreach ($this->events_recent as $i => $e): ?>
<tr class="recent_events hide">
	<td>
		<img src="<?= Alp_Url::img('icon/num/v'.($i+1).'.gif') ?>" />
		<a href="/space_bar/events/view?tid=<?= $e['tid'] ?>">
			<?= stripcslashes($e['title']) ?>
		</a>
	</td>
	<td class="f9 quiet txtr" width="80" valign="top">
		<?= date('y/m/d H:i', $e['starttime']) ?>
	</td>
</tr>
<?php endforeach; ?>
<?php else: ?>
<tr class="recent_events hide">
	<td colspan="2">
		没有记录
	</td>
</tr>
<?php endif; ?>
</table>

<script type="text/javascript">
	function notsartyet()
	{
		$('.nostart_events').show();
		$('.recent_events').hide();
		$('a[href*="notsartyet"]').css({fontWeight:'bold', background:'#fff', padding:'2px 6px 8px 6px'});
		$('a[href*="recentend"]').css({fontWeight:'normal', background:'none', padding:'2px 6px 8px 6px'});
	}
	function recentend()
	{
		$('.nostart_events').hide();
		$('.recent_events').show();
		$('a[href*="recentend"]').css({fontWeight:'bold', background:'#fff', padding:'2px 6px 8px 6px'});
		$('a[href*="notsartyet"]').css({fontWeight:'normal', background:'none', padding:'2px 6px 8px 6px'});
	}
	notsartyet();
</script>