<?php if(count($this->groups) > 0):  ?>
<table width="100%" class="table-dashed">
<tr class="bcolor-z">
	<td>
		<b>精彩群组</b>
	</td>
	<td class="txtr">
		<a href="/space_group/?list=all">&gt;&gt;更多</a>
	</td>
</tr>
<?php foreach ($this->groups as $i => $g): ?>
<?php if($i%2 == 0): ?><tr><?php endif; ?>
	<td width="50%" valign="top">
		<b><a href="/space_group/home/?id=<?= $g['gid'] ?>"><?= stripslashes($g['name']) ?></a></b>
		<br />
		<p class="quiet"><?= $g['intro'] ?></p>
	</td>
<?php if($i%2 == 1): ?></tr><?php endif; ?>
<?php endforeach; ?>
</table>
<?php endif; ?>