<table width="100%" class="table-dashed">
<tr class="bcolor-z">
	<td class="a-span">
		<b>群组贴动态</b>
	</td>
	<td class="txtr"><a href="/space_search/?for=bar&key=&range=group">&gt;&gt;更多</a></td>
</tr>
<?php if(count($this->bars) > 0): foreach ($this->bars as $i => $b): ?>
<tr <?= $i%2==1?'class="bcolor-g"':'' ?>>
	<td colspan="2">
		<img class="vm" src="<?= Alp_Url::img('icon/1616/'.$this->icons[$b['type']]) ?>" />
		<a href="/space_bar/<?= $b['type'] ?>/view?tid=<?= $b['tid'] ?>"><?= Alp_String::utfSubStr(stripcslashes($b['title']),39) ?></a>
	</td>
</tr>
<?php endforeach; else: ?>
<tr><td class="quiet" colspan="2">没找到相关的内容</td></tr>
<?php endif; ?>
</table>