<div style="background:url(<?= Alp_Url::img('v1/home.jpg') ?>); height:160px; width:650px;">
	<div class="f14" style="padding:15px 0 10px 30px;">
		欢迎您光临 <a href="/public/index/doc/of/aboutus"><b>杭州浙江大学校友会</b></a> 
		已经有 <b style="color:#DE4A00">1031638</b> 位校友入住本站！
	</div>
	<?php $v = Alp_Url::img('icon/mix/v.gif'); ?>
	<div class="yui-g" style="font-size:13px; padding-left:10px; color:#444;">
		<div class="yui-u first">
			<dl>
				<dd class="pdb5"><img src="<?= $v ?>" class="mgr10" />在这里，您可以及时了解母校的最新动态</dd>
				<dd class="pdb5"><img src="<?= $v ?>" class="mgr10" />发起或参与校友的各种俱乐部活动</dd>
				<dd class="pdb5"><img src="<?= $v ?>" class="mgr10" />给予和得到来自校友的帮助</dd>
				<dd class="pdb5"><img src="<?= $v ?>" class="mgr10" />拥有只属于浙大校友的互动空间</dd>
			</dl>
		</div>
		<div class="yui-u txtc">
			<a href="/public/reg/">
				<img style="margin-top:50px;" src="<?= Alp_Url::img('v1/reg_btn.gif'); ?>" />
			</a>
		</div>
	</div>
</div>
<br />