<style>
	.corp_box{ float:left; margin:10px 0 5px 55px; border:1px solid #ccc }
	.del_box{ position:absolute; top:0; right:0; z-index:100; background:#fff; }
</style>
<div id="hd" class="yui-g">
	<div class="yui-u first">
		<a href="http://www.zjuhz.com"><img src="/im/v1/logo.gif" /></a>
	</div>
	<div class="yui-u"></div>
</div>
<div id="bd">
	<div id="yui-main">
		<h2 class="section">杭州浙江大学校友会活动赞助企业展示</h2>
		<?php foreach($this->corps as $corp): if($corp['active'] == 1): ?>
		<table class="corp_box">
			<tr>
				<td>
				<div style="position:relative">
					<?php if($this->uid): ?>
					<div class="del_box"><a target="_blank" href="javascript:del(<?= $corp['cid'] ?>)"><img src="<?= Alp_Url::img('icon/classic/del.gif'); ?>" /></a></div>
					<?php endif; ?>
					<a target="_blank" href="/addon_partners/?cid=<?= $corp['cid'] ?>"><img src="<?= Logic_Addon_Partners::Logo($corp['cid']) ?>" /></a>
				</div>
				</td>
			</tr>
			<tr>
				<td class="txtc"><a href="/addon_partners/?cid=<?= $corp['cid'] ?>"><?= $corp['name'] ?></a></td>
			</tr>
		</table>
		<?php endif; endforeach; ?>
		<table class="corp_box">
			<tr>
				<td><a href="/addon_partners/manage/corpcreate">+ 申请加入</a></td>
			</tr>
		</table>
	</div>
</div>
<script>
function del(cid)
{
	var c = confirm('确定删除该企业展示信息？');
	if(c == true)
	$.post(
		'/addon_partners/manage/del?cid='+cid,
		null,
		function(data){ if(data == 'success'){alert('成功删除'); history.go(0); }   }
	);
}
</script>