<div class="yui-main">
    <div class="mg5 section yui-g">
		<div class="yui-u first" style="width:80%">
            <b>目前还不在抽奖有效时间哦~</b>
		</div>
		<div class="yui-u txtr" style="width:20%">
			<a href="javascript:history.back()">返回上一页</a>
		</div>
	</div>
    <div class="txtc"><img src="/im/lucky/nochance.gif" /></div>

    <h1 class="txtc">目前还不在抽奖有效时间哦~</h1>
    <h1 class="txtc" style="color:orange">【有效时间：<?= $this->start_at ?> ~ <?= $this->stop_at ?>】</h1>
</div>