<div class="yui-main">
    <div class="mg5 section yui-g">
		<div class="yui-u first" style="width:80%">
            <b>今天你已经玩过了哦~明天再来吧</b>
		</div>
		<div class="yui-u txtr" style="width:20%">
			<a href="javascript:history.back()">返回上一页</a>
		</div>
	</div>
    <div class="txtc"><img src="/im/lucky/nochance.gif" /></div>

    <h1 class="txtc">
        今天你已经玩过了哦~明天再来吧
        【<a href="/addon_lucky/play/luckymen?id=<?= @$_GET['id'] ?>">幸运者名单</a>】
    </h1>

</div>