<style type="text/css">
.sub { background:#E4EDCF; }
</style>
<h2 class="section">杭州大学生实习联盟 - 个人简历填写</h2>
<form id="resume_form" method="post" onsubmit="return save()">
<table width="100%">
	<tr>
		<td width="20%" valign="top" class="txtc">
			<img class="pd5 mg5" style="border:1px dashed #ccc;" src="<?= Cmd::userhead($this->profile['uid'], 80, $this->profile['sex']) ?>" />
			<br />
			<a href="/space_set/profile/head">上传照片</a>
		</td>
		<td width="80%">
			<table class="table-dashed" width="80%">
				<tr class="sub">
					<td class="f14 bold">基本信息 </td>
					<td class="txtr">
						<a href="/space_set/profile/">
							<img src="/im/icon/1616/profile.gif" class="vm" /> 修改</a>
					</td>
				</tr>
				<tr>
					<td><span class="quiet">姓名：</span><?= $this->profile['username'] ?></td>
					<td><span class="quiet">性别：</span><?= $this->profile['sex'] ?></td>
				</tr>
				<tr class="bcolor-g">
					<td>
						<span class="quiet">专业：</span>
						<input type="text" name="major" value="<?= stripslashes($this->data['major']) ?>" />
					</td>
					<td>
						<span class="quiet">年级：</span>
						<input type="text" name="grade" value="<?= stripslashes($this->data['grade']) ?>" />
					</td>
				</tr>
				<tr>
					<td>
						<span class="quiet">手机：</span>
						<?= $this->profile['mobile'] ? $this->profile['mobile'] : 
						'<a href="/space_set/profile/contact">请填写</a>' ?>
					</td>
					<td>
						<span class="quiet">电话：</span>
						<?= $this->profile['tel'] ?>
					</td>
				</tr>
				<tr class="bcolor-g">
					<td>
						<span class="quiet">邮箱：</span><?= $this->profile['email'] ?>
					</td>
					<td>
						<span class="quiet">住址：</span>
						<?= $this->profile['address'] ? $this->profile['address'] : 
						'<a href="/space_set/profile/contact">请填写</a>' ?>
					</td>	
				</tr>
			</table>
			<!-- 附加信息 -->
			<table class="table-dashed" width="80%">
				<tr class="sub">
					<td class="f14 bold">教育背景（大学本科起）</td>
					<td class="txtr"></td>
				</tr>
				<tr>
					<td class="quiet">每行书写格式： 起至时间、学校名称、科/系、学位</td>
				</tr>
				<tr>
					<td class="quiet" colspan="2">
						<textarea name="edu" style="width:100%;height:50px;"><?= $this->data['edu'] ?></textarea>
					</td>
				</tr>
			</table>
			<table class="table-dashed" width="80%">
				<tr class="sub">
					<td class="f14 bold">培训经历</td>
					<td class="txtr"></td>
				</tr>
				<tr>
					<td class="quiet">每行书写格式： 起止时间、培训名称、资格证书</td>
				</tr>
				<tr>
					<td class="quiet" colspan="2">
						<textarea name="train" style="width:100%;height:50px;"><?= $this->data['train'] ?></textarea>
					</td>
				</tr>
			</table>
			<table class="table-dashed" width="80%">
				<tr class="sub">
					<td class="f14 bold">实习(项目)经历</td>
					<td class="txtr"></td>
				</tr>
				<tr>
					<td class="quiet">每行书写格式： 起止时间、任职单位名称/项目名称、职位</td>
				</tr>
				<tr>
					<td class="quiet" colspan="2">
						<textarea name="internship" style="width:100%;height:50px;"><?= $this->data['internship'] ?></textarea>
					</td>
				</tr>
			</table>
			<table class="table-dashed" width="80%">
				<tr class="sub">
					<td class="f14 bold">获奖情况</td>
					<td class="txtr"></td>
				</tr>
				<tr>
					<td class="quiet">每行书写格式： 获奖时间、所获奖项</td>
				</tr>
				<tr>
					<td class="quiet" colspan="2">
						<textarea name="award" style="width:100%;height:50px;"><?= $this->data['award'] ?></textarea>
					</td>
				</tr>
			</table>
			<table class="table-dashed" width="80%">
				<tr class="sub">
					<td class="f14 bold">其他信息</td>
					<td class="txtr"></td>
				</tr>
				<tr>
					<td class="quiet">个人描述</td>
				</tr>
				<tr>
					<td class="quiet" colspan="2">
						<textarea name="intro" style="width:100%;height:50px;"><?= $this->data['intro'] ?></textarea>
					</td>
				</tr>
				<tr>
					<td class="quiet">你希望自己毕业后从事哪类工作？为了这一目标，你曾做过哪些准备，未来还会怎样努力以达成目标？</td>
				</tr>
				<tr>
					<td class="quiet" colspan="2">
						<textarea name="memo_1" style="width:100%;height:50px;"><?= $this->data['memo_1'] ?></textarea>
					</td>
				</tr>
				<tr>
					<td class="quiet">你希望通过参与本次活动，取得哪些收获？ </td>
				</tr>
				<tr>
					<td class="quiet" colspan="2">
						<textarea name="memo_2" style="width:100%;height:50px;"><?= $this->data['memo_2'] ?></textarea>
					</td>
				</tr>
				<tr>
					<td>
						<input type="submit" value="上传保存" class="btn" />
						<?php if($this->data != false) : ?>
						<input type="hidden" name="update" value="<?= $this->uid ?>" />
						<a href="/addon_league/" class="mgl10" style="border-bottom:1px dashed #ccc">资料已经入库，现在可以进入培训&amp;实习企业搜索页面</a>
						<?php endif; ?>
					</td>
				</tr>
			</table>
		</td>
	</tr>
</table>
</form>

<script type="text/javascript">
	function save()
	{
		$('input:submit').attr('disabled', true).val('正在保存...');
		$.post('/addon_league/resume/save', $('#resume_form').serializeArray(), function(data){
			if(data == 'success') 
			{
				$('input:submit').val('保存成功');
				history.go(0);
			}
			else
			{
				alert(data);
				$('input:submit').attr('disabled', false).val('上传保存');
			}
		});
		return false;
	}
</script>