<?php $this->headTitle(htmlspecialchars(stripcslashes($this->row['title']))); ?>
<div class="yui-main">
	<div class="mg5 section yui-g">
		<div class="yui-u first" style="width:80%">
			<img class="vm mgr10" src="<?= Alp_Url::img('icon/1616/talk.gif') ?>" /><b>新闻快递</b> 
			:: <a href="/space_bar/?type=news&sort=<?= $this->row['sort'] ?>"><?= $this->row['sortname'] ?></a> / <?= stripcslashes($this->row['title']) ?>
		</div>
		<div class="yui-u txtr a-span" style="width:20%">
			<a href="javascript:history.back()">返回上一页</a>
			<a href="/space_bar/?type=news">返回新闻列表</a>
		</div>
	</div>
	<?= $this->action('prenext', 'news', 'space_bar', array('id' => $this->row['tid'])); ?>
	<table width="100%">
		<tr>
			<td>
				<div class="yui-g section-sub">
					<div class="yui-u first" style="width:80%">
						<img class="online_state" src="<?= Alp_Url::img('icon/1616/offline.gif') ?>" rel="<?= $this->row['puber'] ?>" />
						<?php if($this->row['nicky']): ?>
						<?= $this->row['unick'] ?>
						<?php else: ?>
						<a href="/space_home/?uid=<?= $this->row['puber'] ?>"><?= $this->row['uname'] ?></a>
						<?php endif; ?>
					</div>
					<div class="yui-u txtr" style="width:20%">
						<?= Alp_Date::normal($this->row['pubtime']) ?> 
						&nbsp;&nbsp;&nbsp;&nbsp;
						楼主
					</div>
				</div>
				<div class="f14 pd10" style="line-height:150%;">
					<h2 class="txtc"><?= stripcslashes($this->row['title']) ?></h2>
					<?= stripslashes($this->row['content']); ?>
				</div>
				<hr class ="dashed" />
				<br />
				<?= $this->action('prenext', 'news', 'space_bar', array('id' => $this->row['tid'])); ?>
				<br />
				<?= $this->action('relative','news','space_bar',array('tid'=>$this->row['tid'],'tags'=>unserialize($this->row['tags']))); ?>
				<?= $this->render('toolbar.phtml'); ?>
			</td>
		</tr>
	</table>
	<?= $this->action('view', 'comment', 'space_bar') ?>
</div>