<?php $base = Logic_User_Base::get($this->params['uid']); ?>
<div class="yui-main">
	<div class="yui-b">
		<div class="mg5 section yui-g">
			<div class="yui-u first">
				<img class="vm mgr10" src="<?= Alp_Url::img('icon/1616/home.gif') ?>" /><b><?= $base['username'] ?>个人主页</b>
			</div>
			<div class="yui-u txtr"><a href="javascript:history.back()">返回上一页</a></div>
		</div>
		<div class="yui-g">
			<div class="yui-u first" style="width:20%;">
				<div class="head80">
					<img style="margin:20px 0 0 20px" src="<?= Cmd::userhead($this->params['uid'], '80', Cmd::getSess('profile','sex')) ?>" />
				</div>
				<div class="a-span" style="line-height:150%">
					<a href="/sapce_set/detail/">详细资料</a>
					<a href="javascript:friend_add(<?= $this->params['uid'] ?>)">加为好友</a>
					<br />
					<a href="/space_msg/send/?uid=<?= $this->params['uid'] ?>">发送信息</a>
				</div>
				<br /><br />
			</div>
			<div class="yui-u mgt10" style="width:79%;">
				<div class="notice">
					<h2>由于对方的隐私设置，你没有权限查看。</h2>
				</div>
			</div>
		</div>
	</div>
</div>
<?= $this->render('sidebar.phtml'); ?>