<div class="yui-main">
	<div class="yui-b">
		<div class="mg5 section yui-g">
			<div class="yui-u first">
				<img class="vm mgr10" src="<?= Alp_Url::img('icon/1616/rss.gif') ?>" /><b>信息订阅</b>
			</div>
			<div class="yui-u txtr"><a href="javascript:history.back()">返回上一页</a></div>
		</div>
		<div class="tb-box">
			<a href="/space_rss/" <?= $this->tab == 'index'?'class="tb-on"':'class="tb-of"' ?>>RSS订阅</a><span class="tb-rbg"></span>
			<a href="/space_rss/email/" <?= $this->tab == 'email'?'class="tb-on"':'class="tb-of"' ?>>Email订阅</a><span class="tb-rbg"></span>
		</div>