<div class="yui-main">
	<h3 class="section-u">
		<img src="<?= Alp_Url::img('icon/1616/box.gif'); ?>" class="vm mgr10" />最新动态
	</h3>
	<table class="table-dashed" width="100%">
	<?php if(count($this->log) > 0): foreach($this->log as $i => $r): ?>
	<tr <?php if($i%2==1) {echo 'style="background:#f5f5f5"';} ?>>
		<td width="40" valign="top" class="txtr">
			<img src="<?= Alp_Url::img('icon/log/'.$r['key'].'.gif'); ?>" />
		</td>
		<td style="color:#333">
			<a href="/space_home/?uid=<?= $r['uid'] ?>"><?= $r['uname'] ?></a>
			<?= ((int)$r['fid'] > 0) ? ' 将 <a href="/space_home/?uid='.$r['fid'].'">'.$r['fname'].'</a>':'' ?>
			<span class="quiet"><?= $this->event[$r['key']] ?></span>
			<?php if($r['gid'] > 0): ?>
			<a href="/space_group/home/?id=<?= $r['gid'] ?>">[<?= $r['gname'] ?>]</a>
			<?php endif; ?>
			<?php if($r['tid'] > 0): ?>
				<a href="/space_bar/<?= $r['type'] ?>/view?tid=<?= $r['tid'] ?>"><?= $r['title'] ?></a>
				<?= Logic_Space_Bar::subpage($r); ?>
			<?php endif; ?>
			<?php if($r['key'] == 'mod_ing'): ?>
				<img src="<?= Alp_Url::img('icon/log/quote.gif'); ?>" /><?= $r['value'] ?>
			<?php endif; ?>
			<?php if($r['key'] == 'add_reply'): ?>
				<div class="mg5"><img src="<?= Alp_Url::img('icon/log/quote.gif'); ?>" /><?= $r['value'] ?></div>
			<?php endif; ?>
		</td>
		<td width="30%" class="quiet txtr f9" valign="top"><?= date('Y-m-d H:i',$r['time']) ?></td>
	</tr>
	<?php endforeach; else: ?>
	<tr>
		<td class="quiet">尚未有关的信息动态</td>
	</tr>
	<?php endif; ?>
	</table>
</div>