<div class="yui-main">
	<table class="table-dashed" width="100%">
	<?php if(count($this->log) > 0): ?>
	<?= $this->render('dynamic/adduser.phtml'); ?>
	<?= $this->render('dynamic/addfriend.phtml'); ?>
	<?= $this->render('dynamic/group.phtml'); ?>
	<?= $this->render('dynamic/addbar.phtml'); ?>
	<?= $this->render('dynamic/replybar.phtml'); ?>
	<?php else: ?>
	<tr>
		<td class="quiet">尚未有关的信息动态</td>
	</tr>
	<?php endif; ?>
	</table>
</div>
<script type="text/javascript">
	function htab(flag, section)
	{
		if(flag == 1)
		{
			$('#'+section+'_tab').text('+展开').attr('href','javascript:htab(0,"'+section+'")');
			$('.dynameic_'+section).hide();
			setCookie('dynameic_'+section, 0, 7);
		}
		else
		{
			$('#'+section+'_tab').text('-折起').attr('href','javascript:htab(1,"'+section+'")');
			$('.dynameic_'+section).show();
			setCookie('dynameic_'+section, 1, 7);
		}
	}
</script>