<div class="yui-b">
	<div class="greybox">
		<div class="greybox-top"></div>
		<?php if(Cmd::role() != 'guest') echo $this->action(Cmd::role(), 'modnav'); ?>
	</div>
	<br />
	<h3 class="section">最近来访</h3>
		<?php if($this->guests): foreach($this->guests as $r): ?>
		<table width="33%" class="fleft">
			<tr><td>
				<img class="online_state" src="<?= Alp_Url::img('icon/1616/offline.gif') ?>" rel="<?= $r['uid'] ?>" />
				<a href="/space_home/?uid=<?= $r['uid'] ?>"><?= $r['username'] ?></a>
				<div class="quiet f9"><?= date('m/d H:i', $r['time']) ?></div>
			</td></tr>
		</table>
		<?php endforeach; else: ?>
		<div class="quiet mg10">暂时还没人来访</div>
		<?php endif; ?>
	<h3 class="section" style="clear:left;">好友列表</h3>
		<?php if($this->friends): foreach($this->friends as $f): ?>
		<table width="33%" class="fleft">
			<tr><td>
				<img class="online_state" src="<?= Alp_Url::img('icon/1616/offline.gif') ?>" rel="<?= $f['friend'] ?>" />
				<a href="/space_home/?uid=<?= $f['friend'] ?>"><?= $f['uname'] ?></a>
			</td></tr>
		</table>
		<?php endforeach; ?> 
		<div class="txtr" style="clear:left;">
			<a style="color:#666" href="/space_friends/from/?uid=<?= $this->uid ?>">&gt;&gt;所有好友</a>
		</div>
		<?php else: ?>
		<div class="quiet mg10">还没加任何好友</div>
		<?php endif; ?>
</div>
<script type="text/javascript">
	$('.yui-d3f').addClass('yui-t6');
	online_state();
</script>