<div class="yui-main">
	<div class="yui-b">
		<div class="mg5 section yui-g">
			<div class="yui-u first">
				<img class="vm mgr10" src="<?= Alp_Url::img('icon/mix/edit.gif') ?>" /><b>修改新闻</b>
			</div>
			<div class="yui-u txtr"><a href="javascript:history.back()">返回上一页</a></div>
		</div>
		<form id="news_form" method="post" onsubmit="return pub_news()">
		<table class="mgl10 table-dashed" width="97%">
			<tr>
				<td class="txtr">归类：</td>
				<td>
					<select name="sort" id="news_sorts">
						
					</select>
					<input id="new_sort" type="text" name="sortname" value="" />
					<input onclick="create_sort()" type="button" value="创建" class="btn" />
				</td>
			</tr>
			<tr>
				<td class="txtr">标题：</td>
				<td>
					<input type="text" name="title" value="<?= stripslashes($this->row['title']) ?>" size="90" />
				</td>
			</tr>
			<tr>
				<td class="txtr">图片：</td>
				<td id="pic_upload">
				</td>
			</tr>
			<tr>
				<td class="txtr">内容：</td>
				<td><?= Cmd::fck('content',stripslashes($this->row['content']),'300px','99%') ?></td>
			</tr>
			<tr>
				<td class="txtr">关键字：</td>
				<td>
					<span id="tags_input"> 
						<?php 
							$tags = unserialize($this->row['tags']); 
							foreach ($tags as $t) :
						?>
						<input type="text" name="tags[]" size="4" value="<?= $t; ?>" />
						<?php endforeach; ?>
					</span>
					<span id="tags_ext"></span>
					<a href="javascript:add_tags()">增加</a>
				</td>
			</tr>
			<tr>
				<td class="txtr">公开给：</td>
				<td><?= $this->render('mod/private.phtml') ?>
					<?= $this->render('mod/nicky.phtml') ?>
					&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
					<input id="submit" type="submit" value="保存修改" class="btn" />
					<input type="hidden" name="group" value="<?= $this->gp ?>" />
				</td>
			</tr>
		</table>
		</form>
		<iframe name="pic_frame" class="hide" src="/public/upload/pic"></iframe>
	</div>
</div>

<script type="text/javascript">
	function pub_news()
	{
		$('#submit').attr('disabled', true).val('正在保存，请稍候...');
		$('#content').val(FCKeditorAPI.GetInstance("content").GetXHTML());
		$.post(
			'/space_bar/mod/news?tid=<?= $this->row['tid'] ?>',
			$('#news_form').serializeArray(),
			function(data)
			{
				if(data.result == 'success')
				window.location.href = '/space_bar/news/view?tid='+data.tid;
				else 
				{
					alert(data.result);
					$('#submit').attr('disabled', false).val('保存修改');
				}
			},'json'
		);
		return false;
	}
	function create_sort()
	{
		var v = $('#new_sort').val();
		$('.btn[type=button]').attr('disabled', true).val('创建中...');
		$.post(
			'/space_bar/news/create_sort',
			{sortname:v},
			function(data)
			{
				if(data == 'success')
				{
					$('#news_sorts').load('/space_bar/news/sorts');
					$('.btn[type=button]').attr('disabled', false).val('创建成功');
				}
				else 
				{
					alert(data);
					$('.btn[type=button]').attr('disabled', false).val('创建');
				}
			}
		);
	}
	function add_tags()
	{
		$('#tags_input').after('<input type="text" name="tags[]" size="4" /> ');
	}
	function insert_html(html){FCKeditorAPI.GetInstance("content").InsertHtml(html);upreload();}
	$('#pic_upload').load('/public/upload/form?for=pic');
	$('#news_sorts').load('/space_bar/news/sorts?sort=<?= $this->row['sort'] ?>');
</script>