<select name="private">
	<?php if(!$this->gp): ?>
	<option value="0" <?= $this->row['private'] == 0 ? 'selected="selected"':'' ?>>仅自己</option>
	<option value="1" <?= $this->row['private'] == 1 ? 'selected="selected"':'' ?>>仅好友</option>
	<option value="3" <?= $this->row['private'] == 3 ? 'selected="selected"':'' ?>>仅校友</option>
	<option value="4" <?= $this->row['private'] == 4 ? 'selected="selected"':'' ?>>所有人</option>
	<?php else: ?>
	<option value="0" <?= $this->row['private'] == 0 ? 'selected="selected"':'' ?>>仅自己</option>
	<option value="1" <?= $this->row['private'] == 1 ? 'selected="selected"':'' ?>>仅好友</option>
	<option value="2" <?= $this->row['private'] == 2 ? 'selected="selected"':'' ?>>仅群组成员</option>
	<option value="3" <?= $this->row['private'] == 3 ? 'selected="selected"':'' ?>>仅校友</option>
	<?php endif; ?>
</select>