<table class="table-dashed mgl10">
	<?php foreach ($this->sorts as $i => $s): ?>
	<tr>
		<td class="mgl10">
			<?php if(isset($this->default[$i])): ?>
				<input class="item" type="text" value="<?= $s ?>" disabled="disabled" />
			<?php else: ?>
				<input class="item" type="text" value="<?= $s ?>"  />
				<input type="button" class="btn" value="保存" />
				<input type="button" class="btn" value="删除" />
			<?php endif; ?>
		</td>
	</tr>
	<?php endforeach; ?>
	<tr>
		<td class="mgl10">
			<input type="text" id="new_item" value=""  />
			<input onclick="create_sort()" type="button" id="create_btn" class="btn" value="添加" />
		</td>
	</tr>
</table>

<script type="text/javascript">
	function create_sort()
	{
		var len = $('.item').length;
		var val = $('#new_item').val();
		$('#create_btn').val('添加中..').attr('disabled', true);
		$.post('/space_friends/sort/create', {sid:(len+1),val:val}, function(data){
			if(data == 'success') history.go(0);
			else{ alert(data); $('#create_btn').val('添加').attr('disabled', false); }
		});
	}
</script>