<div class="yui-main">
	<div class="yui-b">
		<div class="mg5 section yui-g">
			<div class="yui-u first" style="width:80%">
				<img class="vm mgr10" src="<?= Alp_Url::img('icon/1616/talk.gif') ?>" /><b>公共帖吧</b>
				 :: 自动收集校友发布的新闻、活动、话题、互助...方便您的查阅交流
			</div>
			<div class="yui-u txtr" style="width:20%"><a href="javascript:history.back()">返回上一页</a></div>
		</div>
		<?= $this->render('tab.phtml'); ?>
		<hr class="dashed" />
	</div>
</div>