CREATE TABLE [party] (
[id] INTEGER  PRIMARY KEY AUTOINCREMENT NOT NULL,
[title] VARCHAR(90)  NOT NULL,
[time] INTEGER  NOT NULL,
[content] TEXT  NOT NULL,
[ticket] INTEGER  NOT NULL,
[left] INTEGER  NOT NULL,
[member] TEXT  NULL,
[password] VARCHAR(32)  NOT NULL,
[limit] INTEGER  NOT NULL
);

CREATE TABLE [station] (
[id] INTEGER  NOT NULL PRIMARY KEY AUTOINCREMENT,
[pid] INTEGER  NOT NULL,
[address] VARCHAR(100)  NOT NULL
);
