CREATE TABLE [corporation] (
[cid] INTEGER  PRIMARY KEY AUTOINCREMENT NOT NULL,
[uid] INTEGER  NOT NULL,
[name] VARCHAR(200)  UNIQUE NOT NULL,
[intro] TEXT  NOT NULL,
[time] INTEGER  NOT NULL,
[tel] VARCHAR(50)  NULL,
[address] VARCHAR(200)  NULL,
[website] VARCHAR(100)  NULL,
[contact] VARCHAR(12)  NOT NULL,
[active] BOOLEAN  NOT NULL
);

CREATE TABLE [user] (
[uid] INTEGER  PRIMARY KEY AUTOINCREMENT NOT NULL,
[username] VARCHAR(16)  UNIQUE NOT NULL,
[password] VARCHAR(32)  NOT NULL
);