<div class="yui-main">
	<div class="yui-b">
		<div class="mg5 section yui-g">
			<div class="yui-u first">
				<img class="vm mgr10" src="<?= Alp_Url::img('icon/1616/group.gif') ?>" />
				<b><?= stripslashes($this->group['name']); ?></b>
			</div>
			<div class="yui-u txtr a-span">
				<a href="javascript:history.back()">返回上一页</a>
			</div>
		</div>
		<?= $this->action('info', 'home', 'space_group', array('group'=>$this->group)); ?>
		<?= $this->render('tab.phtml'); ?>
		<!-- 群帖子快速一览 -->
		<?= $this->action('topic', 'home', 'space_group'); ?>
	</div>
</div>
<?= $this->render('home/sidebar.phtml'); ?>