<div class="yui-b">
	<div class="greybox">
		<div class="greybox-top"></div>
		<?php if(Cmd::role() != 'guest') echo $this->action(Cmd::role(), 'modnav'); ?>
	</div>
	<br />
	<h3 class="section">创建人与管理员</h3>
	<table width="24%" class="fleft">
		<tr><td>
			<div class="head40">
				<a href="/space_home/?uid=<?= $this->creater['uid'] ?>">
					<img class="mg10" src="<?= Cmd::userhead($this->creater['uid']) ?>" />
				</a>
			</div>
			<img class="online_state" src="<?= Alp_Url::img('icon/1616/offline.gif') ?>" rel="<?= $this->creater['uid'] ?>" />
			<a href="/space_home/?uid=<?= $this->creater['uid'] ?>"><?= $this->creater['username'] ?></a>
		</td></tr>
	</table>
	<?php foreach ($this->manager as $m): ?>
	<table width="33%" class="fleft">
		<tr><td>
			<div class="head40">
				<a href="/space_home/?uid=<?= $m['uid'] ?>">
					<img class="mg10" src="<?= Cmd::userhead($m['uid']) ?>" />
				</a>
			</div>
			<img class="online_state" src="<?= Alp_Url::img('icon/1616/offline.gif') ?>" rel="<?= $m['uid'] ?>" />
			<a href="/space_home/?uid=<?= $m['uid'] ?>"><?= $m['username'] ?></a>
		</td></tr>
	</table>
	<?php endforeach; ?>
	<h3 class="section" style="clear:left;">新加入成员</h3>
	<?php foreach ($this->fresh as $f): ?>
	<table width="33%" class="fleft">
		<tr><td>
			<div class="head40">
				<a href="/space_home/?uid=<?= $f['uid'] ?>">
					<img class="mg10" src="<?= Cmd::userhead($f['uid']) ?>" />
				</a>
			</div>
			<img class="online_state" src="<?= Alp_Url::img('icon/1616/offline.gif') ?>" rel="<?= $f['uid'] ?>" />
			<a href="/space_home/?uid=<?= $f['uid'] ?>"><?= $f['username'] ?></a>
		</td></tr>
	</table>
	<?php endforeach; ?>
	<h3 class="section" style="clear:left;">最近访问成员</h3>
	<?php foreach ($this->visitor as $v): ?>
	<table width="33%" class="fleft">
		<tr><td>
			<div class="head40">
				<a href="/space_home/?uid=<?= $v['uid'] ?>">
					<img class="mg10" src="<?= Cmd::userhead($v['uid']) ?>" />
				</a>
			</div>
			<img class="online_state" src="<?= Alp_Url::img('icon/1616/offline.gif') ?>" rel="<?= $v['uid'] ?>" />
			<a href="/space_home/?uid=<?= $v['uid'] ?>"><?= $v['username'] ?></a>
		</td></tr>
	</table>
	<?php endforeach; ?>
</div>

<script type="text/javascript">
	$('.yui-d3f').addClass('yui-t6')
	online_state();
</script>