<?php $cache = Logic_Cache::factory('Output', 3600); $uid = Cmd::uid(); ?>
<?php if(!$cache->start('group_'.$this->gid.'point')): ?>
<div style="color:#D44848; padding:3px;">
	<img src="/im/icon/1616/heart.gif" /> 群热度:
	<?php Logic_Space_Group::countpoint($this->gid); ?>
	<?= Logic_Space_Group::degree($this->gid).'°C' ?>
</div>
<?php $cache->end(); endif; ?>

<?php if($this->type != 'close' && !$this->role): ?>
	<a href="javascript:joinGroup()" class="blk"><img class="vm" src="<?= Alp_Url::img('icon/1616/door.gif') ?>" /> 加入该群</a>
<?php endif; ?>

<?php if($this->type != 'close' && $this->role == 'join'): ?>
	<span class="quiet">已申请加入，等待处理</span>
<?php endif; ?>

<?php if($this->type == 'close' && ($this->role == 'manager' || $this->role == 'creater')): ?>
	<a href="/space_group/invite/?gid=<?= $this->gid ?>" class="blk"><img class="vm" src="<?= Alp_Url::img('icon/1616/add_m.gif') ?>" /> 邀请好友加入群</a>
<?php endif; ?>

<?php if($this->type != 'close' && $this->role && $this->role != 'join' && $this->role != 'invite'): ?>
	<a href="/space_group/invite/?gid=<?= $this->gid ?>" class="blk"><img class="vm" src="<?= Alp_Url::img('icon/1616/add_m.gif') ?>" /> 邀请好友加入群</a>
<?php endif; ?>

<?php if($this->role == 'invite'): ?>
	<a href="javascript:invite_pass(<?= $this->gid.','.$uid ?>)" class="blk"><img class="vm" src="<?= Alp_Url::img('icon/1616/door.gif') ?>" /> 接受邀请加入群</a>
<script type="text/javascript">
function invite_pass(gid)
{
	$.post('/space_group/member/ipass', {gid:gid}, function(data){ 
		if(data == 'success') history.go(0);
	});
}
</script>
<?php endif; ?>

<?php if($this->role == 'member'): ?>
	<a href="javascript:leaveGroup(<?= Cmd::uid() ?>)" class="blk"><img class="vm" src="<?= Alp_Url::img('icon/1616/out.gif') ?>" /> 脱离该群</a>
<?php endif; ?>

<?php if($this->role == 'creater' || $this->role == 'manager'): ?>
	<a href="/space_group/manage/?id=<?= $this->gid ?>" class="blk"><img class="vm" src="<?= Alp_Url::img('icon/1616/mana.gif') ?>" /> 管理该群</a>
<?php endif; ?>

<?php if($this->role == 'creater') : ?>
	<a href="javascript:dgroup(<?= $this->gid ?>)" class="blk"><img class="vm" src="<?= Alp_Url::img('icon/1616/rbs.gif') ?>" /> 删除该群</a>
<?php endif; ?>

<script type="text/javascript">
function joinGroup(){ $.post('/space_group/member/join/',{id:<?= $this->gid ?>}, function(data){$.facebox(data);});}
function leaveGroup(uid){ 
	var c = confirm('确定要脱离？相关的群组消息也会自动删除'); 
	if(c == true) {
		$.post('/space_group/member/leave/',{uid:uid, id:<?= $this->gid ?>}, 
		function(data){if(data == 'success') location.href='/space_group/'});
	}
}
function dgroup(id){ 
	var c = confirm("确定要删除该群组么？里面的成员以及帖子都会删除");
	if(c == true)
	$.post('/space_group/home/del', {gid:id}, 
	function(data){ if(data == 'success') location.href='/space_group/'; else alert(data); }) 
}
</script>