<div class="section f14"><img src="<?= Alp_Url::img('icon/1616/f_doc.gif') ?>" /> 网站内部文件上传</div>
<form class="pd10 f14" target="system_file" action="/public/upload/system" method="post" enctype="multipart/form-data" onsubmit="uping()">
请选择要上传的文件：
<input size="50" type="file" name="file[]" />
<input type="hidden" name="dir" value="<?= $this->params['dir'] ?>" />
<input id="upbtn" type="submit" value="上传" class="btn" /> 
<br /><br />
<span class="quiet">支持rar,zip,doc,xls,ppt,7z,mp3,pdf | 文件上限2MB</span>
</form>
<iframe name="system_file" class="hide"></iframe>
<script type="text/javascript">
function uping(){$('#upbtn').attr('disabled', true).val('上传中..');}
function upreload(){$('#upbtn').attr('disabled', false).val('上传');}
</script>