<div class="yui-g mgt10">
	<!-- 我的群组列表 -->
	<div class="yui-u first" style="width:32%">
	<?php
		if(count($this->groups) > 0):
		$gname = array();
		foreach ($this->groups as $g):
		$gname[$g['gid']] = $g['name'];
	?>
	<table class="mgl10 table-dashed">
		<tr>
			<td width="30">
				<a href="/space_group/home/?id=<?= $g['gid'] ?>">
					<img width="30" class="cccborder" src="<?= Cmd::groupicon($g['gid'], 40) ?>" />
				</a>
			</td>
			<td>
				<a href="/space_group/home/?id=<?= $g['gid'] ?>"><b><?= $g['name'] ?></b></a><br />
				<a href="/space_bar/?pub=topic&gp=<?= $g['gid'] ?>" style="color:#666">[发帖]</a>
				<?php if($g['role'] == 'creater' || $g['role'] == 'manager'): ?>
				<a href="/space_group/manage/?id=<?= $g['gid'] ?>" style="color:#666">[管理]</a>
				<?php endif; ?>
			</td>
		</tr>
	</table>
	<?php endforeach; else: ?>
	<table class="mg10 table-dashed">
		<tr><td class="quiet">你还没有加入任何群组</td></tr>
	</table>
	<?php endif; ?>
	</div>
	
	<!-- 我的群组最新话题列表 -->
	<div class="yui-u" style="width:68%;">
	<?php if(count($this->bars) > 0) : ?>
		<table class="table-dashed" width="100%">
			<?php foreach ($this->bars as $i => $b): ?>
			<tr <?= $i%2==1?'class="bcolor-g"':'' ?>>
				<td>
					<img src="<?= Alp_Url::img('icon/1616/'.$this->icons[$b['type']]) ?>" />
					<a style="color:#666" href="/space_group/home/?id=<?= $b['group'] ?>">
						[<?= $gname[$b['group']] ?>]</a>
					<a href="/space_bar/<?= $b['type'] ?>/view?tid=<?= $b['tid'] ?>">
						<?= stripslashes($b['title']) ?>
					</a>
					<?= Logic_Space_Bar::subpage($b); ?>
					<span class="quiet f9"><?= Alp_Date::normal($b['replytime']) ?></span>
				</td>
			</tr>
			<?php endforeach; ?>
		</table>
	<?php endif; ?>
	</div>
</div>


