<div class="yui-main">
	<div class="yui-b">
		<div class="mg5 section yui-g">
			<div class="yui-u first">
				<img class="mgr10" src="<?= Alp_Url::img('icon/1616/mail.gif') ?>" />
				<b>站内消息(私密对话)</b>
			</div>
			<div class="yui-u txtr"><a href="javascript:history.back()">返回上一页</a></div>
		</div>
		<?= $this->render('index/type.phtml'); ?>
		<br />
		<form id="pm_form" method="post" onsubmit="return postmsg()">
			<table width="90%">
				<tr>
					<td class="txtr">发送给：</td>
					<td>
						<div id="incept_box" style="position:relative;">
						<input name="uname" id="uname_box" type="text" value="<?= $this->incept['username'] ?>" size="70" /> 
						<a href="javascript:friends_box()">发送对象</a>
							<span id="friends_box"></span>
						</div>
					</td>
				</tr>
				<tr>
					<td class="txtr">内容：</td>
					<td>
						<textarea name="content" style="width:380px; height:200px"></textarea>
					</td>
				</tr>
				<tr>
					<td colspan="2" class="txtc">
						<input class="btn" type="submit" value="确定发送" />
					</td>
				</tr>
			</table>
			<input id="incepter" type="hidden" name="incept" value="<?= $this->incept['uid'] ?>" />
		</form>
		
	</div>
</div>
<div class="yui-b">
	<div class="greybox mgb10">
		<div class="greybox-top"></div>
		<?php if(Cmd::role() != 'guest') echo $this->action(Cmd::role(), 'modnav'); ?>
	</div>
</div>

<script type="text/javascript">
	function postmsg(){
		$('input:submit').val('发送中..').attr('disabled', true);
		$.post('/space_msg/pm/post', $('#pm_form').serializeArray(), function(data){
			if(data != 'success') {alert(data); $('input:submit').val('确定发送').attr('disabled', false);}
			else $('input:submit').val('发送成功');
		});
		return false;
	}
	$('.yui-d3f').addClass('yui-t6');
	function friends_box(){ $('#friends_box').load('/space_msg/pm/friends'); }
</script>