<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="verify-v1" content="ZGUEnxQZ/X/BNNiS9oEW+nBoAAIgE0bnomsFgREbpoE=" />
    <meta http-equiv="X-UA-Compatible" content="IE=7" />
    <?= $this->headTitle('杭州浙江大学校友会_zjuhz.com')->setSeparator('_'); ?>
    <script type="text/javascript" src="/js/common.js"></script>
    <?= $this->headScript() ?>
    <link rel="stylesheet" type="text/css" href="/cs/v1.css" />
    <?= $this->headLink() ?>
    <script type="text/javascript">
    //document.domain = "zjuhz.com";
    </script>
</head>
<body>
<div class="yui-d3f">
    <div id="hd" class="yui-g">
        <div class="yui-u first" style="width:200px">
            <a href="/"><img src="/im/v1/logo.gif" /></a>
        </div>
        <div class="yui-u hd-r" style="width:580px">
            <?= $this->partial('topnav.phtml') ?>
        </div>
    </div>
    <div id="bd">
    <?= $this->layout()->content ?>
    </div>

		<div id="ft-l"></div>
		<div id="ft-r"></div>

    <div id="ft">
        <?= $this->partial('footer.phtml') ?>
    </div>
</div>

<script type="text/javascript">
<?php 
	$tips = Cmd::getSess('apt_tip');
	if(count($tips) > 0 && $_COOKIE['apt_tip'] != 'no'):
	$data = Zend_Json::encode($tips);
?>
$.post('/api_json/msg/apt', <?= $data ?>, function(data){ $.facebox(data) });
<?php endif; Cmd::setSess('apt_tip', null);  ?>
check_msgbox();
var msgbox = window.setInterval("check_msgbox()", 30000);
</script>


<script type="text/javascript">
var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
try {
var pageTracker = _gat._getTracker("UA-399951-3");
pageTracker._trackPageview();
} catch(err) {}</script>


<?php //setcookie("crossid", session_id(), time()+3600, "/", ".zjuhz.com"); ?>
</body>
</html>
