<p class="a-span txtr" style="line-height:180%">
    <a href="#">使用帮助</a>
    <a href="/public/index/doc/of/aboutus">关于我们</a>
    <a href="/public/index/doc/of/privacyclaim">隐私声明</a>
    <a href="#">网站建议</a>
    <a href="http://www.miibeian.gov.cn" target="_blank">浙ICP备08109401号</a>
    <br />
    地址：杭州市西溪路525号浙大科技园C楼608&nbsp;&nbsp;&nbsp;
    电话：0571-8998 8185/8998 8186&nbsp;&nbsp;&nbsp;
    传真：0571-8512 1608&nbsp;&nbsp;&nbsp;
    杭州浙江大学校友会&copy;2008
</p>