<div class="txtr f12">
	<?php if(Cmd::role() == 'guest'): ?>
	<table width="100%">
    	<tr>
    		<td class="txtl">
    			<span style="color:#aaa">
    				本站目标：成为校友沟通互助的平台和助手<br />
    				本会宗旨：联络校友 帮助校友 回报母校 建设杭州
    			</span>
    		</td>
    		<td class="pd10" valign="top">
    			<?php if(isset($_COOKIE['zjuhz_remember'])):
    				$key = unserialize(stripslashes(Alp_String::decrypt($_COOKIE['zjuhz_remember'])));
    			?>
    			<span id="login_hook"><img src="<?= Alp_Url::img('icon/loading/v3.gif'); ?>" /> 尝试自动登陆中...</span>
    			<script type="text/javascript">
    				$.getJSON(
				        '/public/login/dologin',
				        {sid:'<?= Zend_Session::getId() ?>',account:'<?= $key[0] ?>',password:'<?= $key[1] ?>',rememberme:1},
				        function(data){ 
				        	if(data.form_tip == 'success')
				        	history.go(0);
				        }
				    );
    			</script>
    			<?php else: ?>
    			<a href="/public/login/"><img src="<?= Alp_Url::img('icon/1616/offline.gif') ?>" /> 登录</a>
    			<?php endif; ?>
			    <a href="/public/login/findpsw"><img src="<?= Alp_Url::img('icon/1616/find_key.gif') ?>" /> 找密码</a>
			    <a href="/public/reg/"><img src="<?= Alp_Url::img('icon/1616/new_key.gif') ?>" /> 注册</a>
    		</td>
    	</tr>
    </table>
    <?php else: ?>
    <table>
    	<tr>
    		<td class="a-span5">
    			<p class="mgb5" style="height:18px;">
    				Hi~ <b><?= Cmd::getSess('profile', 'username') ?></b> 
    				[<?= Cmd::rolename() ?>]
    				<span id="logout">
    					<a href="javascript:logout(0)"><img class="vm" src="<?= Alp_Url::img('icon/1616/out.gif') ?>" />退出</a>
	    			</span>
	    			<span id="logout_confirm" class="hide quiet">
	    				确定退出?
	    				<a href="javascript:logout(1)"><img class="vm" src="<?= Alp_Url::img('icon/mix/v.gif') ?>" />是</a> 
	    				<a href="javascript:logout(2)"><img class="vm" src="<?= Alp_Url::img('icon/mix/x.gif') ?>" />否</a> 
	    			</span>
    			</p>
    			<a href=""><img class="vm" src="<?= Alp_Url::img('icon/1616/mail.gif') ?>" />消息[0]</a>
    			<a href=""><img class="vm" src="<?= Alp_Url::img('/icon/1616/heart.gif') ?>" />热心度</a>
    			<a href=""><img class="vm" src="<?= Alp_Url::img('icon/1616/profile.gif') ?>" />设置</a>
    			<a href=""><img class="vm" src="<?= Alp_Url::img('icon/1616/home.gif') ?>" />主页</a>
    		</td>
    		<td width="10%">
    			<div class="head40"><img class="pd10" src="<?= Cmd::userhead(Cmd::uid()) ?>" /></div>
    		</td>
    	</tr>
    </table>
    <?php endif; ?>
</div>

<script type="text/javascript">
	function logout(t)
	{
		if(t == 0){ $('#logout').hide(); $('#logout_confirm').show(); }
		if(t == 1){ location.href="/public/login/out"; }
		if(t == 2){ $('#logout').show(); $('#logout_confirm').hide(); }
	}
</script>