<?= $this->render('head.phtml'); ?>
<div id="bd">
	<div class="yui-main">
		<br />
		<hr class="dashed" />
			<b class="step">第一步：修改企业Logo，企业名称</b> &nbsp;&nbsp;&nbsp;
			<b class="step">第二步：修改企业Banner</b> &nbsp;&nbsp;&nbsp;
			<b class="step">第三步：修改企业简介</b> &nbsp;&nbsp;&nbsp;
			<b class="step">第四步：修改企业联系方式</b> &nbsp;&nbsp;&nbsp;
			<b class="step">完成：更新企业原有数据</b>
		<hr class="dashed" />
		<?= $this->render('manage/setup'.$this->step.'.phtml'); ?>
	</div>
</div>

<div id="ft-l"></div>
<div id="ft-r"></div>

<script>
	$('.step').css('color','#ccc');
	$('.step:eq(<?= $this->step ?>)').css('color','#64931D');
	
	function step(n)
	{
		location.href='/addon_partners/manage/corpmodify?step='+n;
	}
	function cancel()
	{
		location.href='/addon_partners/manage/corplist?uid=<?= $this->uid ?>';
	}
</script>