<div id="bd">
	<div id="yui-main">
		<br /><br /><br />
		<h2 class="mgl10">修改企业信息</h2>
		<hr class="dashed" />
			<b class="step">第一步：修改企业Logo，企业名称</b> &nbsp;&nbsp;&nbsp;
			<b class="step">第二步：修改企业Banner</b> &nbsp;&nbsp;&nbsp;
			<b class="step">第三步：修改企业简介</b> &nbsp;&nbsp;&nbsp;
			<b class="step">第四步：修改企业联系方式</b> &nbsp;&nbsp;&nbsp;
			<b class="step">完成：更新企业原有数据</b>
		<hr class="dashed" />
		<?= $this->render('manage/setup'.$this->step.'.phtml'); ?>
	</div>
</div>
<script>
	$('.step').css('color','#ccc');
	$('.step:eq(<?= $this->step ?>)').css('color','#64931D');
	
	function step(n)
	{
		location.href='/addon_partners/manage/corpmodify?step='+n;
	}
	function insert_html(html)
	{
		window.frames["Editor"].window.frames["HtmlEditor"].document.getElementsByTagName("BODY")[0].innerHTML += html;
	}
	function get_content()
	{
		window.frames["Editor"].AttachSubmit();
	}
	function cancel()
	{
		location.href='/addon_partners/manage/corplist?uid=<?= $this->uid ?>';
	}
</script>