<?= $this->headTitle('添加新企业信息'); ?>
<div id="bd">
	<div id="yui-main">
		<br /><br /><br />
		<h2>添加新企业信息</h2>
		<hr class="dashed" />
			<b class="step">第一步：上传企业LOGO，提交企业名称</b> &nbsp;&nbsp;&nbsp;
			<b class="step">第二步：提交企业简介以及近期情况</b> &nbsp;&nbsp;&nbsp;
			<b class="step">第三步：提交企业联系方式</b>
		<hr class="dashed" />
	</div>
</div>
<script>
	$('.step').css('color','#ccc');
	$('.step:eq(<?= $this->step ?>)').css('color','#64931D');
</script>