<form action="/addon_partners/manage/setup1" target="banner_upload" method="post" enctype="multipart/form-data">
	<table class="mgt10">
		<tr>
			<?php $banner = Logic_Addon_Partners::setupBanner($this->uid); ?>
			<?php if($banner == '/upload/addon/partners/banner/default.gif' && $this->cid): ?>
			<td><img src="<?= Logic_Addon_Partners::banner($this->cid); ?>" /></td>
			<?php else: ?>
			<td><img id="banner" src="<?= Logic_Addon_Partners::setupBanner($this->uid); ?>" /></td>
			<?php endif; ?>
		</tr>
		<tr>
			<td>
				<p class="quiet">企业 banner 图片有效格式为gif,png,jpg[尺寸最好为950*115像素]</p>
				<input type="file" name="banner[]" size="20" />
			</td>
		</tr>
		<tr>
			<td class="txtr">
				<input onclick="cancel()" class="btn" type="button" value="取消" />
				<input onclick="step(0)" class="btn" type="button" value="上一步" />
				<input class="btn" type="submit" value="下一步" />
			</td>
		</tr>
	</table>
</form>
<iframe class="hide" name="banner_upload"></iframe>
<script>
	function change_banner(file)
	{
		var date = new Date();
		$('#banner').attr('src','/upload/addon/partners/banner/'+file+'?'+date.getTime());
	}
</script>