<form action="/addon_partners/manage/setup0" target="logo_upload" method="post" enctype="multipart/form-data">
	<table class="mgt10">
		<tr>
			<?php $logo = Logic_Addon_Partners::setupLogo($this->uid); ?>
			<?php if($this->cid && $logo == '/upload/addon/partners/logos/default.gif'): ?>
			<td><img src="<?= Logic_Addon_Partners::logo($this->cid); ?>" /></td>
			<?php else: ?>
			<td><img id="logo" src="<?= $logo ?>" /></td>
			<?php endif; ?>
			<td>
				<p class="quiet">企业 logo 图片有效格式为gif,png,jpg[尺寸最好为220*78像素]</p>
				<input type="file" name="logo[]" size="20" />
				<br /><br />
				企业名称：<input type="text" name="name" value="<?= $this->name ?>" style="width:350px" />
			</td>
		</tr>
		<tr>
			<td colspan="2"><hr class="dashed" /></td>
		</tr>
		<tr>
			<td></td>
			<td class="txtr">
				<input onclick="cancel()" class="btn" type="button" value="取消" />
				<input class="btn" type="submit" value="下一步" />
			</td>
		</tr>
	</table>
</form>
<iframe class="hide" id="logo_upload" name="logo_upload"></iframe>
<script>
	function change_logo(file)
	{
		var date = new Date();
		$('#logo').attr('src','/upload/addon/partners/logos/'+file+'?'+date.getTime());
	}
</script>