<div class="mods yui-g">
	<div class="yui-u first">
		<img src="<?= Alp_Url::img('icon/1616/talk.gif') ?>" class="vm" />
		<a href="/space_bar/">公共帖吧</a>
	</div>
	<div class="yui-u">
		<img src="<?= Alp_Url::img('icon/1616/news.gif') ?>" class="vm" />
		<a href="/space_bar/?type=news">新闻快递</a>
	</div>
	<div class="yui-u first">
		<img src="<?= Alp_Url::img('icon/1616/tea.gif') ?>" class="vm" />
		<a href="/space_bar/?type=events">校友活动</a>
	</div>
	<div class="yui-u">
		<img src="<?= Alp_Url::img('icon/1616/smile.gif') ?>" class="vm" />
		<a href="/space_bar/?type=help">校友互助</a>
	</div>
	<div class="yui-u first">
		<img src="<?= Alp_Url::img('icon/1616/vote.gif') ?>" class="vm" />
		<a href="/space_bar/?type=vote">投票调查</a>
	</div>
	<div class="yui-u">
		<img src="<?= Alp_Url::img('icon/1616/pic.gif') ?>" class="vm" />
		<a href="/space_bar/?type=photo">看图论事</a>
	</div>
	<div class="yui-u first">
		<img src="<?= Alp_Url::img('icon/1616/share.gif') ?>" class="vm" />
		<a href="/space_bar/?type=share">文件共享</a>
	</div>
	<div class="yui-u">
		<img src="<?= Alp_Url::img('icon/1616/group.gif') ?>" class="vm" />
		<a href="/space_group/">群组俱乐部</a>
	</div>
</div>
	
<?php if(Cmd::role() == 'bench'): ?>
	<?= $this->controllername; ?>
<?php endif; ?>
	
<?php if(Cmd::role() == 'black'): ?>
<br />
<b><?= 	Cmd::rolename() ?>附加权限：</b>
<div class="mods yui-g">
	<div class="yui-u first">
		<img src="<?= Alp_Url::img('icon/1616/inf.gif') ?>" class="vm" />
		<a href="">申请解冻</a>
	</div>
</div>
<?php endif; ?>

<?php if(Cmd::role() != 'black' && Cmd::role() != 'bench'): ?>
<br />
<b>正式成员权限：</b>
<div class="mods yui-g">
	<div class="yui-u first">
		<img src="<?= Alp_Url::img('icon/1616/search.gif') ?>" class="vm" />
		<a href="">全站搜索</a>
	</div>
	<div class="yui-u">
		<img src="<?= Alp_Url::img('icon/1616/friend.gif') ?>" class="vm" />
		<a href="">我的好友</a>
	</div>
</div>
<?php endif; ?>
	
<?php if(Cmd::role() == 'power'): ?>
<br />
<b><?= 	Cmd::rolename() ?>附加权限：</b>
<div class="mods yui-g">
	<div class="yui-u first">
		<img src="<?= Alp_Url::img('icon/1616/s_mail.gif') ?>" class="vm" />
		<a href="">群发消息</a>
	</div>
</div>
<?php endif; ?>
	
<?php if(Cmd::role() == 'master'): ?>
<br />
<b><?= 	Cmd::rolename() ?>附加权限：</b>
<div class="mods yui-g">
	<div class="yui-u first">
		<img src="<?= Alp_Url::img('icon/1616/f_user.gif') ?>" class="vm" />
		<a href="">用户管理</a>
	</div>
	<div class="yui-u">
		<img src="<?= Alp_Url::img('icon/1616/f_doc.gif') ?>" class="vm" />
		<a href="">帖子管理</a>
	</div>
	<div class="yui-u first">
		<img src="<?= Alp_Url::img('icon/1616/f_heart.gif') ?>" class="vm" />
		<a href="">热心度管理</a>
	</div>
	<div class="yui-u">
		<img src="<?= Alp_Url::img('icon/1616/s_mail.gif') ?>" class="vm" />
		<a href="">群发消息</a>
	</div>
</div>
<?php endif; ?>
<hr class="dashed" />