<div class="yui-main">
	<div class="section-u">
		<img src="<?= Alp_Url::img('icon/1616/box.gif'); ?>" class="vm mgr10" />
		<b>好友动态</b>
	</div>
	
	<div class="section-u">
		<img src="<?= Alp_Url::img('icon/1616/box.gif'); ?>" class="vm mgr10" />
		<b>空间动态</b>
	</div>
	
	<div class="section-u">
		<img src="<?= Alp_Url::img('icon/1616/gbook.gif'); ?>" class="vm mgr10" />
		<b>留言本</b>
	</div>
</div>