<div class="yui-main">
	<div class="yui-b">
		<div class="mg5 section yui-g">
			<div class="yui-u first">
				<img class="vm mgr10" src="<?= Alp_Url::img('icon/1616/home.gif') ?>" /><b>我的个人主页</b>
			</div>
			<div class="yui-u txtr"><a href="javascript:history.back()">返回上一页</a></div>
		</div>
		<?= $this->render('my/profile.phtml'); ?>
		<?= $this->render('my/dynamic.phtml'); ?>
	</div>
</div>
<?= $this->render('sidebar.phtml'); ?>