<?= $this->render('bar/range.phtml') ?>
		<table width="100%" class="table-dashed">
			<tr class="bcolor-g">
				<td class="quiet">找到<?= $this->numrows ?>条记录</td>
				<td></td>
				<td></td>
			</tr>
			<?php if(count($this->rows)): foreach($this->rows as $i => $r): ?>
			<tr <?= $i%2==1?'class="bcolor-g"':'' ?>>
				<td>
					<img src="<?= Alp_Url::img('icon/1616/'.$this->icons[$r['type']]) ?>" />
					<a <?= $r['ding'] == 1?'style="color:red"':'' ?> target="_blank" href="/space_bar/<?= $r['type'] ?>/view?tid=<?= $r['tid'] ?>">
						<?= stripslashes($r['title']); ?>
					</a>
				</td>
				<td class="txtl" width="110">
					<input onclick="this.focus();this.select()" type="text" class="f9" value="<?= date('y/m/d H:i', $r['pubtime']) ?>" size="12" />
					<a href="">改</a>
				</td>
				<td id="bar_<?= $r['tid'] ?>" class="a-span5" width="150">
					<?php if($r['type'] != 'help'): ?>
					<a target="_blank" href="/space_bar/mod/<?= $r['type'] ?>?tid=<?= $r['tid'] ?>&gp=<?= $r['group'] ?>">编辑</a>
					<?php endif; if($r['ding'] == 1): ?>
					<a href="javascript:unding(<?= $r['tid'] ?>)">取消顶置</a>
					<?php else: ?>
					<a href="javascript:ding(<?= $r['tid'] ?>)">顶置</a>
					<?php endif; if($r['deny'] == 1): ?>
					<a href="javascript:undeny(<?= $r['tid'] ?>)">取消屏蔽</a>
					<?php else: ?>
					<a href="javascript:deny(<?= $r['tid'] ?>)">屏蔽</a>
					<?php endif; ?>
				</td>
			</tr>
			<?php endforeach; endif; ?>
		</table>
		<div class="pg"><?= $this->pagination ?></div>
	</div>
</div>
<?= $this->render('sidebar.phtml') ?>

<script type="text/javascript">
function ding(tid){ 
	$.post('/console/bar/update?t=ding&tid='+tid, function(data){
		if(data == 'success')
		{ $('#bar_'+tid+' a:contains("顶置")').text('取消顶置').attr('href', 'javascript:unding('+tid+')'); }
		else alert(data);
	}); 
}
function unding(tid){ 
	$.post('/console/bar/update?t=unding&tid='+tid, function(data){
		if(data == 'success')
		{ $('#bar_'+tid+' a:contains("取消顶置")').text('顶置').attr('href', 'javascript:ding('+tid+')'); }
		else alert(data);
	}); 
}
function deny(tid){ 
	$.post('/console/bar/update?t=deny&tid='+tid, function(data){
		if(data == 'success')
		{ $('#bar_'+tid+' a:contains("屏蔽")').text('取消屏蔽').attr('href', 'javascript:undeny('+tid+')'); }
		else alert(data);
	}); 
}
function undeny(tid){ 
	$.post('/console/bar/update?t=undeny&tid='+tid, function(data){
		if(data == 'success')
		{ $('#bar_'+tid+' a:contains("取消屏蔽")').text('屏蔽').attr('href', 'javascript:deny('+tid+')'); }
		else alert(data);
	}); 
}
</script>