<table width="100%" class="mgt10 table-dashed">
	<tr class="bcolor-g">
		<td width="120">类名</td>
		<td>该类下帖数</td>
		<td></td>
	</tr>
	<?php if(count($this->sorts) > 0): foreach ($this->sorts as $s): ?>
	<tr>
		<td><input id="sort_<?= $s['sort'] ?>" type="text" name="sname" value="<?= $s['name'] ?>" /></td>
		<td><a target="_blank" href="/space_bar/?sort=<?= $s['sort'] ?>&type=help"><?= $s['rate'] ?>篇</a></td>
		<td class="a-span5">
			<a href="javascript:mname(<?= $s['sort'] ?>)">改名</a>
			<?php if($s['rate'] > 0): ?>
			<a href="javascript:mvbar(<?= $s['sort'] ?>)">转移</a>
			<?php else: ?>
			<a href="javascript:dsort(<?= $s['sort'] ?>)">删除</a>
			<?php endif; ?>
		</td>
	</tr>
	<?php endforeach; else: ?>
	<tr>
		<td class="quiet" colspan="3">还没有建立任何求助归类</td>
	</tr>
	<?php endif; ?>
	<tr>
		<td colspan="3">
			<select name="sort" id="help_sorts"></select>
			<input id="help_sort" type="text" name="sortname" value="" />
			<input onclick="create_sort()" type="button" value="创建" class="btn" />
		</td>
	</tr>
</table>
</div>
</div>
<?= $this->render('sidebar.phtml') ?>

<script type="text/javascript">
	function mvbar(sid)
	{
		$.post('/console/bar/mvbar?for=help', {sid:sid}, function(data){
			$.facebox(data);
		});
	}
	
	function mname(sid)
	{
		var sortname = $('#sort_'+sid).val();
		$.post('/console/bar/mname?for=help', {sid:sid,sortname:sortname}, function(data){
			if(data == 'success') { alert('修改成功'); history.go(0); }
			else alert(data);
		});
	}

	function create_sort()
	{
		var v = $('#help_sort').val();
		$('.btn[type=button]').attr('disabled', true).val('创建中...');
		$.post(
			'/space_bar/help/create_sort',
			{sortname:v},
			function(data)
			{
				if(data == 'success')
				{
					$('#help_sorts').load('/space_bar/help/sorts');
					$('.btn[type=button]').attr('disabled', false).val('创建成功');
				}
				else 
				{
					alert(data);
					$('.btn[type=button]').attr('disabled', false).val('创建');
				}
				
			}
		);
	}
	$('#help_sorts').load('/space_bar/help/sorts');
</script>