<?php foreach ($this->rows as $r): ?>
<table class="table-dashed" width="90%" style="line-height:170%">
	<tr>
		<td width="50">
			<div class="head40">
	    		<img class="pd10" src="<?= Cmd::userhead($r['sender'], '40', $r['ssex']) ?>" />
	    	</div>
		</td>
		<td>
			<a href="/space_home/?uid=<?= $r['sender'] ?>"><?= $r['sname'] ?></a> 
			<a style="color:#999" href="/space_group/home/?id=<?= $r['gid'] ?>">[<?= $r['gname'] ?>]</a>
			<span class="quiet"><?= Alp_Date::normal($r['time']) ?>：</span>
			<br />
			<img src="<?= Alp_Url::img('icon/mix/quote2.gif') ?>" />
			<?= stripslashes($r['content']); ?>
		</td>
		<td width="180" id="msg_g_<?= $r['sender'] ?>" <?= ($r['isread'] == 0)?'style="background:url('.Alp_Url::img('v1/newmsg.gif').') no-repeat right bottom"':'' ?>>
			<?php if($r['content'] == '申请加入群'): ?>
				<?php if(Logic_Space_Group_Member::isMemeber($r['gid'], $r['sender'])): ?>
				<div class="success">已批准加入</div>
				<?php else: ?>
				<input onclick="join_pass(<?= $r['gid'].','.$r['sender'] ?>)" class="btn" type="button" value="同意" /> 
				<?php endif; ?>
			<?php endif; ?>
			
			<?php if($r['content'] == '邀请加入群'): ?>
				<?php if(Logic_Space_Group_Member::isMemeber($r['gid'], $r['incept'])): ?>
				<div class="success">已同意加入</div>
				<?php else: ?>
				<input onclick="invite_pass(<?= $r['gid'].','.$r['sender'] ?>)" class="btn" type="button" value="同意" /> 
				<?php endif; ?>
			<?php endif; ?>
		</td>
	</tr>
</table>
<?php endforeach; ?>

<div class="pagination"><?= $this->pagination ?></div>

<script type="text/javascript">
	function join_pass(gid, uid)
	{
		$('#msg_g_'+uid+' .btn').attr('disabled', true);
		$.post('/space_group/member/jpass', {uid:uid,gid:gid}, function(data){ 
			if(data == 'success')
			$('#msg_g_'+uid).html('<div class="success">已批准加入</div>');
		}) 
	}
	
	function invite_pass(gid, uid)
	{
		$('#msg_g_'+uid+' .btn').attr('disabled', true);
		$.post('/space_group/member/ipass', {uid:uid,gid:gid}, function(data){ 
			if(data == 'success')
			$('#msg_g_'+uid).html('<div class="success">已同意加入</div>');
		}) 
	}
</script>