<div class="yui-main">
	<div class="yui-b">
		<div class="mg5 section yui-g">
			<div class="yui-u first" style="width:80%">
				<img class="vm mgr10" src="<?= Alp_Url::img('icon/1616/heart.gif') ?>" />
				<b>校友会热心度</b>
			</div>
			<div class="yui-u txtr" style="width:20%"><a href="javascript:history.back()">返回上一页</a></div>
		</div>
		<div class="tb-box">
			<a href="/public/point/?tab=summary" <?= ($this->tab == 'summary')?'class="tb-on"':'class="tb-of"' ?>>基本摘要</a><span class="tb-rbg"></span>
			<a href="/public/point/?tab=log" <?= ($this->tab == 'log')?'class="tb-on"':'class="tb-of"' ?>>增长记录</a><span class="tb-rbg"></span>
			<a href="/public/point/?tab=award" <?= ($this->tab == 'award')?'class="tb-on"':'class="tb-of"' ?>>申请</a><span class="tb-rbg"></span>
		<a href="/public/point/?tab=alog" <?= ($this->tab == 'alog')?'class="tb-on"':'class="tb-of"' ?>>申请记录</a><span class="tb-rbg"></span>
		</div>
		<?= $this->action($this->tab, 'point', 'public'); ?>
		</div>
</div>
<?= $this->render('sidebar.phtml') ?>