<div class="yui-main">
	<div class="yui-b">
		<div class="mg5 section yui-g">
			<div class="yui-u first">
				<img class="vm mgr10" src="<?= Alp_Url::img('icon/1616/group.gif') ?>" />
				<b><?= stripslashes($this->group['name']); ?>成员</b>
			</div>
			<div class="yui-u txtr a-span">
				<a href="javascript:history.back()">返回上一页</a>
			</div>
		</div>
		<?= $this->render('tab.phtml'); ?>
			<table class="table-dashed mg10" width="98%">
				<tr>
					<td colspan="3">
						
					</td>
				</tr>
				<tr class="section-sub">
					<td width="100">姓名</td>
					<td width="50">身份</td>
					<td width="100">加入时间</td>
					<td class="txtc">操作</td>
				</tr>
				<?php if(count($this->rows) > 0): foreach ($this->rows as $r): ?>
				<tr id="m_<?= $r['uid'] ?>">
					<td>
						<a href="/space_home/?uid=<?= $r['uid'] ?>">
							<img class="vm" width="30" height="30" src="<?= Cmd::userhead($r['uid'], '40', $r['sex']) ?>" />
						</a>
						<a href="/space_home/?uid=<?= $r['uid'] ?>">
							<?= $r['uname'] ?>
						</a>
					</td>
					<td class="quiet">
						<?php 
							$op = '';
							switch ($r['role']){
								case 'member' : 
									$role = '成员';
								break;
								case 'manager' : 
									$role = '管理员';
								break;
							} 
							echo $role;
						?>
					</td>
					<td class="quiet">
						<?= Alp_Date::normal($r['jointime']); ?>
					</td>
					<td class="a-span txtc">
						<a href="/space_msg/pm/?uid=<?= $r['uid'] ?>">@发信</a>
					</td>
				</tr>
				<?php endforeach; else: ?>
				<tr><td colspan="3" class="quiet">没有找到对应群成员</td></tr>
				<?php endif; ?>
			</table>
		<div class="pg"><?= $this->pagination ?></div>
	</div>
</div>
<div class="yui-b">
	<div class="greybox">
		<div class="greybox-top"></div>
		<?php if(Cmd::role() != 'guest') echo $this->action(Cmd::role(), 'modnav'); ?>
	</div>
</div>

<script type="text/javascript">
	$('.yui-d3f').addClass('yui-t6')
</script>