<div class="yui-main">
	<div class="yui-b">
		<div class="mg5 section yui-g">
			<div class="yui-u first">
				<img class="mgr10 vm" src="<?= Alp_Url::img('icon/1616/mail.gif') ?>" />
				<b>消息中心</b>
			</div>
			<div class="yui-u txtr"><a href="javascript:history.back()">返回上一页</a></div>
		</div>
		<?= $this->render('index/type.phtml'); ?>
		<?= $this->render('index/'.$this->type.'.phtml'); ?>
	</div>
</div>
<?= $this->render('sidebar.phtml'); ?>
<script>newMsg(0);</script>