<?php foreach ($this->rows as $r): ?>
<table id="msg_box_<?= $r['mid'] ?>" class="table-dashed" width="90%" style="line-height:170%">
	<tr>
		<td width="50" valign="top">
			<div class="head40">
	    		<img class="pd10" src="<?= Cmd::userhead($r['incept'], '40', $r['isex']) ?>" />
	    	</div>
		</td>
		<td>
			<span class="quiet"><?= Alp_Date::normal($r['time']) ?></span> 发给
			<a href="/space_home/?uid=<?= $r['incept'] ?>"><?= $r['iname'] ?></a> 的
			<?php switch ($r['type']){
				case 'friend' :
					echo '<span class="quiet">好友请求</span>';
				break;
				case 'pm' :
					echo '<span class="quiet">消息</span>';
				break;
				case 'group' : 
					echo '<span class="quiet">群组消息</span>';
				break;
			} ?>
			<?= ($r['isread'] == 0)?'<span class="quiet">(未读)</span>':'' ?>
			<a href="javascript:clear(<?= $r['mid'] ?>)" class="f9" style="color:#666">[x]</a>
			<br />
			<img src="<?= Alp_Url::img('icon/mix/quote2.gif') ?>" />
			<?= stripslashes($r['content']); ?>
		</td>
	</tr>
</table>
<?php endforeach; ?>
<p class="mgl10 quiet a-span">
	共发送过<?= $this->numrows ?>条短消息 
	<a href="javascript:clearSBox()">清空发件箱内已读信息</a>
</p>
<hr class="dashed" />
<div class="pg"><?= $this->pagination ?></div>
<script>
	function clearSBox(){ $.post('/space_msg/index/clearsbox/',function(data){ if(data == 'success') history.go(0); else alert(data); }); }
</script>
