<?php $uid = Cmd::uid(); ?>
<div class="mglr10 tb-box" style="height:28px;overflow:hidden">
	<a href="/space_msg/pm/" <?= ($this->type == 'send')?'class="tb-on"':'class="tb-of"' ?> style="color:#6C950F">发信</a><span class="tb-rbg"></span>
	<a href="/space_msg/?type=pm" <?= ($this->type == 'pm')?'class="tb-on"':'class="tb-of"' ?>>收件箱(<?= Logic_Space_Msg::hasnew($uid, 'pm') ?>)</a><span class="tb-rbg"></span>
	<a href="/space_msg/?type=gbook" <?= ($this->type == 'gbook')?'class="tb-on"':'class="tb-of"' ?>>留言板(<?= Logic_Space_Msg::hasnew($uid, 'gbook') ?>)</a><span class="tb-rbg"></span>
	<a href="/space_msg/?type=friend" <?= ($this->type == 'friend')?'class="tb-on"':'class="tb-of"' ?>>好友请求(<?= Logic_Space_Msg::hasnew($uid, 'friend') ?>)</a><span class="tb-rbg"></span>
	<a href="/space_msg/?type=group" <?= ($this->type == 'group')?'class="tb-on"':'class="tb-of"' ?>>群组消息(<?= Logic_Space_Msg::hasnew($uid, 'group') ?>)</a><span class="tb-rbg"></span>
	<a href="/space_msg/?type=sendbox" <?= ($this->type == 'sendbox')?'class="tb-on"':'class="tb-of"' ?>>发件箱</a><span class="tb-rbg"></span>
</div>
