<table width="100%" class="table-dashed mgt10 oplink">
<tr class="bcolor-z">
	<td class="a-span">
		<b>衷心鸣谢&amp;友情链接</b>
	</td>
	<td class="txtr"><a href="/public/link/">&gt;&gt;更多</a></td>
</tr>
<tr>
	<td><a target="_blank" href="http://www.chinayaojiang.com/cpzx/wdy/index.asp"><img src="<?= Alp_Url::img('logo/yjwdy.gif') ?>" /></a></td>
	<td><a target="_blank" href="/addon_partners/?cid=5"><img src="<?= Alp_Url::img('logo/jsyh.gif') ?>" /></a></td>
</tr>
<tr>
	<td><a target="_blank" href="http://www.bankcomm.com/"><img src="<?= Alp_Url::img('logo/jtyh.gif') ?>" /></a></td>
	<td><a target="_blank" href="http://www.lohoson.com/"><img src="<?= Alp_Url::img('logo/6h.gif') ?>" /></a></td>
</tr>
<tr>
	<td><a target="_blank" href="http://www.greenlander.com.cn/"><img src="<?= Alp_Url::img('logo/greenlander.gif') ?>" /></a></td>
	<td></td>
</tr>
</table>
<script>oplink()</script>