<?php if(count($this->groups) > 0):  ?>
<table width="100%" class="table-dashed">
<tr class="bcolor-z">
	<td>
		<b>精彩群组</b>
	</td>
	<td class="txtr">
		<a href="/space_group/?list=all">&gt;&gt;更多</a>
	</td>
</tr>
<tr><td colspan="2">
<div style="line-height:200%">
<?php foreach ($this->groups as $i => $g): ?>
<a style="color:#<?= $i%2==0?'5D7115':'3F6378' ?>" href="/space_group/home/?id=<?= $g['gid'] ?>"><?= stripslashes($g['name']) ?></a>
&nbsp;&nbsp;&nbsp;
<?php endforeach; ?>
</div>
</td></tr>
</table>
<?php endif; ?>