<div class="yui-main">
	<div class="yui-b">
	<?= Cmd::role() == 'guest' ? $this->render('index/start.phtml'):$this->render('index/welcome.phtml'); ?>
	<?= $this->render('index/fresh.phtml'); ?>
	</div>
</div>
<div class="yui-b">
	<div class="greybox mgl5">
		<div class="greybox-top"></div>
		<?php 
			if(Cmd::role() != 'guest') 
			echo $this->action(Cmd::role(), 'modnav'); 
			else 
			echo $this->render('index/fastlogin.phtml');
		?>
	</div>
	<br />
	<div class="mgl5">
	<?= $this->action('bars', 'index'); ?>
	<?= $this->action('group', 'index'); ?>
	</div>
</div>

<script type="text/javascript">
	$('.yui-d3f').addClass('yui-t6')
</script>