<form id="login_form" method="post" onsubmit="return login()">
	<table>
		<tr>
			<td class="txtr">账号：</td>
			<td><input tabindex="1" type="text" name="username" size="20" /> <a href="/addon_partners/user?goto=create">创建新用户</a></td>
		</tr>
		<tr>
			<td class="txtr">密码：</td>
			<td><input tabindex="2" type="password" name="password" size="20" /></td>
		</tr>
		<tr>
			<td></td>
			<td><input class="btn" id="submit" type="submit" value="登 陆" /></td>
		</tr>
	</table>
	<span id="post_tip"></span>	
</form>
<script>
	function login()
	{
		$('#submit').val('登陆中...').attr('disabled', true);
		$.post(
			'/addon_partners/user/dologin',
			$('#login_form').serializeArray(),
			function(data)
			{
				$('#post_tip').html(data);
				$('#submit').val('登 陆').attr('disabled', false);
			}
		);
		return false;
	}
</script>