<form class="a-span">
<div class="yui-g">
	<div class="yui-u first pdl5" style="width:60%">
		范围:
		<?php 
			$r = $this->range; $k = urlencode($this->key); 
			$on = 'style="text-decoration:underline;color:#333"'; 
		?>
		<a href="/console/user/?key=<?= $k ?>&range=all" <?= ($r == 'all')?$on:'' ?>>全部</a>
		<a href="/console/user/?key=<?= $k ?>&range=black" <?= ($r == 'black')?$on:'' ?>>被冻结</a>
		<a href="/console/user/?key=<?= $k ?>&range=bench" <?= ($r == 'bench')?$on:'' ?>>待审核</a>
		<a href="/console/user/?key=<?= $k ?>&range=member" <?= ($r == 'member')?$on:'' ?>>校友</a>
		<a href="/console/user/?key=<?= $k ?>&range=power" <?= ($r == 'power')?$on:'' ?>>校友会成员</a>
		<a href="/console/user/?key=<?= $k ?>&range=master" <?= ($r == 'master')?$on:'' ?>>管理员</a>
	</div>
	<div class="yui-u a-span txtr" style="width:35%">
		<input type="hidden" name="range" value="<?= $r ?>" />
		<input onclick="this.focus();this.select()" type="text" name="key" value="<?= urldecode($k) ?>" />
		<input class="btn" type="submit" value="搜索" />
	</div>
</div>
</form>