<table width="100%">
  <tr>
    <td id="photo_box" class="txtc">
    
    </td>
  </tr>
  <tr>
    <td colspan="3" id="intro_box" class="quiet pd10" style="background:#f5f5f5"></td>
  </tr>
</table>

<div class="txtc">
<?php foreach ($this->photos as $p): ?>
<a href="javascript:void(0)">
	<?php if(file_exists(UPLOADROOT.'photo/'.$this->puber.'/'.Alp_String::appendFileName($p['file'], '_resize'))): ?>
	<img title="<?= stripcslashes($p['intro']); ?>" class="photo_item pd10" src="<?= Alp_Url::upload('photo/'.$this->puber.'/'.Alp_String::appendFileName($p['file'], '_resize')) ?>" width="80" />
	<?php else: ?>
	<img title="<?= stripcslashes($p['intro']); ?>" class="photo_item pd10" src="<?= Alp_Url::upload('photo/'.$this->puber.'/'.$p['file']) ?>" width="80" />
	<?php endif; ?>
</a>
<?php endforeach; ?>
</div>



<script type="text/javascript">
	$('.photo_item').click(function(){
		$('.photo_item').css('border','none');
		$(this).css('border','1px solid #444');
		var url = $(this).attr('src');
		var intro = $(this).attr('title');
		$('#photo_box').html('<img src="'+url+'" />');
		$('#intro_box').html(intro);
	});
	$('.photo_item:first').click();
</script>