<table width="100%">
  <tr>
  	<td class="txtr" width="40">
  		<a href="javascript:javascript:prev_item()"><img class="selector" src="<?= Alp_Url::img('v1/arr-l.gif'); ?>" /></a>
  	</td>
    <td id="photo_box" class="txtc" width="600" style="border:1px solid #666">
    
    </td>
    <td width="40">
    	<a href="javascript:next_item()"><img class="selector" src="<?= Alp_Url::img('v1/arr-r.gif'); ?>" /></a>
    </td>
    <td valign="top">
  		<div class="txtc" style="height:400px; overflow:auto">
		<?php foreach ($this->photos as $i => $p): ?>
		<a href="javascript:this_item(<?= $i ?>)">
			<?php if(file_exists(UPLOADROOT.'photo/'.$this->puber.'/'.Alp_String::appendFileName($p['file'], '_resize'))): ?>
			<img class="photo_item pd5" src="<?= Alp_Url::upload('photo/'.$this->puber.'/'.Alp_String::appendFileName($p['file'], '_resize')) ?>" width="80" />
			<?php else: ?>
			<img class="photo_item pd5" src="<?= Alp_Url::upload('photo/'.$this->puber.'/'.$p['file']) ?>" width="80" />
			<?php endif; ?>
		</a>
		<textarea class="hide" id="photo_intro_<?= $i ?>"><?= stripcslashes($p['intro']); ?></textarea>
		<?php endforeach; ?>
		</div>
  	</td>
  </tr>
</table>
<input type="hidden" id="cur_item" />
<div id="intro_box" class="pd10"></div>



<script type="text/javascript">
	$('.selector').css('opacity', 0.5).mouseover(function(){$(this).fadeTo('fast', 0.8)}).mouseout(function(){$(this).fadeTo('fast', 0.5)});
	function prev_item()
	{
		var cur = parseInt($('#cur_item').val());
		if(cur != 0)
		this_item(cur - 1);
	}
	function next_item()
	{
		var pnum = $('.photo_item').length;
		var cur = parseInt($('#cur_item').val());
		if((cur+1) != pnum)
		this_item(cur + 1);
	}
	function this_item(i)
	{
		var cur_item = $('.photo_item:eq('+i+')');
		$('.photo_item').css('border','1px solid #fff');
		cur_item.css('border','1px solid #444');
		var url = cur_item.attr('src');
		$('#photo_box').html('<a target="_blank" href="'+url.replace(/_resize/,'')+'"><img src="'+url+'" /></a>');
		$('#intro_box').html($('#photo_intro_'+i).text());
		$('#cur_item').val(i);
	}
	this_item(0);
</script>