<form action="/addon_partners/manage/setup0" target="logo_upload" method="post" enctype="multipart/form-data">
	<table class="mgt10">
		<tr>
			<td><img id="logo" src="<?= Logic_Addon_Partners::setupLogo($this->uid); ?>" /></td>
			<td>
				<p class="quiet">企业 logo 图片格式必须为 gif,png,jpg</p>
				<input type="file" name="logo[]" size="20" />
				<br /><br />
				企业名称：<input type="text" name="name" value="<?= $this->name ?>" size="50" />
			</td>
		</tr>
		<tr>
			<td colspan="2"><hr class="dashed" /></td>
		</tr>
		<tr>
			<td></td>
			<td class="txtr">
				<input class="btn" type="button" value="取消" />
				<input class="btn" type="submit" value="下一步" />
			</td>
		</tr>
	</table>
</form>
<iframe class="hide" id="logo_upload" name="logo_upload"></iframe>
<script>
	function change_logo(file)
	{
		var date = new Date();
		$('#logo').attr('src','/upload/addon/partners/logos/'+file+'?'+date.getTime());
	}
</script>