<form id="uploader" target="file_upload" action="/addon_partners/manage/upload" method="post" enctype="multipart/form-data">
<table>
	<tr>
		<td class="txtr">图片上传：</td>
		<td><input type="file" name="file[]" /> <input class="btn" type="button" onclick="$('#uploader').submit();" value="上传" /></td>
	</tr>
</table>
</form>
<form id="intro_form" target="file_upload" action="/addon_partners/manage/setup2" method="post">
	<?= Cmd::fck('intro', $this->intro); ?>
	<p class="txtr">
		<input onclick="cancel()" class="btn" type="button" value="取消" />
		<input onclick="step(1)" class="btn" type="button" value="上一步" />
		<input class="btn" type="submit" value="下一步" />
	</p>
</form>
<iframe class="hide" id="file_upload" name="file_upload"></iframe>
<script>
	function insert_html(html)
	{
		var oEditor = FCKeditorAPI.GetInstance("intro");
		oEditor.InsertHtml(html);
	}
</script>