<div class="yui-g">
	<div class="yui-u first" style="width:10%"></div>
	<div class="yui-u" style="width:90%">
		<h2 class="section-u">欢迎使用密码找回系统</h2>
		<p class="quiet pd5">如您忘记了自己的邮箱地址，可以输入真实姓名按下“检查”我们会罗列出对应的邮箱地址。
		如果您的帐号原先没有设置过邮箱请来电联系。</p>
		<form id="password_form" method="post" onsubmit="return send_psw()">
			<table>
				<tr>
					<td><b>真实姓名</b></td>
		            <td>
		                <input id="username" size="30" type="text" name="username" maxlength="4" /> 
		                <input onclick="emco()" type="button" class="btn" value="检查" />
		            </td>
				</tr>
				<tr>
		            <td><b>电子邮箱</b></td>
		            <td>
		                <input size="30" type="text" name="email" maxlength="40" />
		            </td>
		        </tr>
		        <tr>
		            <td><b>密码重设</b></td>
		            <td>
		                <input size="30" type="text" name="password" />
		            </td>
		        </tr>
		        <tr>
		        	<td colspan="2" class="txtc">
		        		<input class="btn" type="submit" value="确定，发送重设密码邮件" />
		        		<input type="hidden" name="code" value="<?= Alp_String::encrypy(Zend_Session::getId()) ?>" />
		        	</td>
		        </tr>
			</table>
		</form>
	</div>
</div>
<script type="text/javascript">
	function send_psw()
	{
		$('input:submit').val('发送邮件中...请等待').attr('disabled', true);
		$.post('/public/password/send', $('#password_form').serializeArray(), function(data){
			if(data == 'success') $('input:submit').val('发送成功，请尽快前去查收');
			else { alert(data); $('input:submit').val('重新发送').attr('disabled', false); }
		});
		return false;
	}
	function emco()
	{
		var name = $('#username').val();
		$.post('/public/password/checkout/', {username:name}, function(data){
			$.facebox(data);
		});
	}
</script>