<h2 class="section">杭州大学生实习联盟 - 实习岗位&amp;培训搜索</h2>
<form method="get">
	<?php if($this->resume == false): ?>
	<div class="error">系统检测到你还没有填写报名所需的<a class="bold" href="/addon_league/resume/">简历信息</a>，请先填写后再进行搜索报名操作~谢谢合作。</div>
	<?php else: ?>
	<div class="success">你已完成简历信息的提交，如需要修改可以<a class="bold" href="/addon_league/resume/">点击此处</a></div>
	<?php endif; ?>
	<p class="pd5">
		<a href="/addon_league">显示全部</a>
		<select name="region">
			<option value="">地区：</option>
		<?php if(count($this->regions) > 0): foreach($this->regions as $r): ?>
			<option value="<?= $r['region'] ?>" 
			<?= $r['region'] == $this->params['region'] ? 'selected="selected"':'' ?>><?= $r['region'] ?></option>
		<?php endforeach; endif; ?>
		</select>

		<select name="trade">
			<option value="">行业：</option>
		<?php if(count($this->trades) > 0): foreach($this->trades as $t): ?>
			<option value="<?= $t['trade'] ?>" 
			<?= $t['trade'] == $this->params['trade'] ? 'selected="selected"':'' ?>><?= $t['trade'] ?></option>
		<?php endforeach; endif; ?>
		</select>

		<select name="func">
			<option value="">职能：</option>
			<?php foreach ($this->func as $fc): ?>
			<option value="<?= $fc ?>" <?= $this->params['func'] == $fc ? 'selected="selected"':'' ?>><?= $fc ?></option>
			<?php endforeach; ?>
		</select>
		&nbsp;&nbsp;&nbsp;&nbsp;
		岗位：
		<input name="job" value="<?= stripcslashes($this->params['job']) ?>" size="5" />
		&nbsp;&nbsp;&nbsp;&nbsp;
		企业：
		<input name="name" value="<?= stripcslashes($this->params['name']) ?>" size="25" />
		<input class="btn" type="submit" value="搜索" />
		<?php if($this->role == 'master' || $this->role == 'power'): ?>
		<input type="button" class="btn" onclick="location.href='/addon_league/mana'" value="添加" />
		<a href="/addon_league/resume/list">简历列表</a>
		<?php endif; ?>
	</p>
</form>

<table class="table-dashed" width="100%">
<tr class="bcolor-g">
	<td>地区</td>
	<td>行业</td>
	<td>职能</td>
	<td>企业名称</td>
	<td class="txtc">联系人</td>
	<td class="txtc">岗位名额 / 已报名数</td>
	<td></td>
</tr>
<?php if(count($this->rows) > 0): foreach ($this->rows as $i => $r): ?>
<tr id="c_<?= $r['corp_id'] ?>" <?= $i%2 == 1 ? 'class="bcolor-g"':'' ?>>
	<td width="7%"><a href="/addon_league/?region=<?= urlencode($r['region']) ?>"><?= $r['region'] ?></a></td>
	<td width="20%"><a href="/addon_league/?trade=<?= urlencode($r['trade']) ?>"><?= $r['trade'] ?></a></td>
	<td><a href="/addon_league/?func=<?= urlencode($r['func']) ?>"><?= $r['func'] ?></a></td>
	<td>
		<a target="_blank" href="<?= $r['web'] ?>"><?= $r['name'] ?></a>
		<a style="color:#666" href="/addon_league/index/intro?id=<?= $r['corp_id'] ?>" rel="facebox">[岗位简介]</a>
		<br />
		<span class="quiet">岗位：</span><?= stripslashes($r['job']) ?>
	</td>
	<td class="txtc"><?php $user = Logic_User_Base::getByAccount($r['contacter']); echo '<a href="/space_set/detail/?uid='.$user['uid'].'">'.$user['username'].'</a>' ?></td>
	<?php $tid = explode('=', strstr($r['url'], 'tid=')); ?>
	<td class="signbox txtc" rel="<?= $tid[1] ?>"></td>
	<td class="a-span">
		<a class="f14 bold" target="_blank" href="<?= $r['url'] ?>#sign_btn">报名</a>
		<?php if(Cmd::role() == 'master'): ?>
		<a href="/addon_league/mana/?mode=update&id=<?= $r['corp_id'] ?>">修改</a>
		<a href="javascript:corp_del(<?= $r['corp_id'] ?>)">删除</a>
		<?php endif; ?>
	</td>
</tr>
<?php endforeach; else: ?>
<tr>
	<td class="quiet">没有找到符合的企业</td>
</tr>
<?php endif; ?>
</table>
<p class="quiet f12 pdl10">共找到<?= $this->numrows ?>条记录</p>
<div class="pg"><?= $this->pagination ?></div>

<script type="text/javascript">
	$('.signbox').each(function(i){ 
		var tid = $(this).attr('rel'); 
		$(this).html('loading..');
		$(this).load('/addon_league/index/signbox?tid='+tid); 
	});
	<?php if(Cmd::role() == 'master'): ?>
	function corp_del(id)
	{
		var c = confirm('确定要删除么？');
		if(c == true)
		{
			$.post('/addon_league/mana/docorp/?mode=delete&id='+id, 
			function(){ $('#c_'+id).fadeOut(); });
		}
	}
	<?php endif; ?>
	$(document).ready(function($){$('a[rel*=facebox]').facebox()});
</script>