<?= $this->render('bar/range.phtml'); ?>
<table class="table-dashed mg5" width="98%">
	<tr class="section-sub">
		<td width="50%">标题</td>
		<td width="15%" class="txtc">作者</td>
		<td width="20%" class="txtc">回复/点击/顶</td>
		<td width="15%" class="txtc">最后发表</td>
	</tr>
	<?php if($this->rows): foreach($this->rows as $i => $r): ?>
	<tr <?= ($i%2 == 1) ? 'bgcolor="#f5f5f5"' : '' ?>>
		<td class="txtl">
			<img class="vm" src="<?= Alp_Url::img('icon/1616/'.$this->icons[$r['type']]); ?>" />
			<?php if($r['group'] > 0): 
				  if($r['gtype'] == 'close') {$m = Logic_Space_Group_Member::isMemeber($r['group'], Cmd::uid());} ?>
				<a href="/space_group/home/?id=<?= $r['group'] ?>" style="color:#666">[<?= $r['gname'] ?>]</a>
			<?php endif; if($r['gtype'] != 'close' || $m): ?>
			<a <?= ($r['ding'] == 1)?'style="color:red"':''; ?> href="/space_bar/<?= $r['type'] ?>/view?tid=<?= $r['tid'] ?>"><?= stripslashes($r['title']) ?></a>
			<?= Logic_Space_Bar::subpage($r); ?>
			<?php else: ?>
			<span class="quiet">非私密群成员，无法显示标题</span>
			<?php endif; ?>
		</td>
		<td class="txtc quiet">
			<?= ($r['nicky']) ? $r['pubnick']:'<a href="/space_home/?uid='.$r['puber'].'">'.$r['pubname'].'</a>' ?><br />
			<span class="tp5"><?= Alp_Date::normal($r['pubtime']) ?></span>
		</td>
		<td class="txtc quiet">
			<span class="tp7"><?= $r['reply'] ?></span> / <?= $r['click'] ?> / <span class="tp3"><?= $r['rate'] ?></span>
		</td>
		<td class="txtc quiet">
			<?= ($r['replytime']) ? Alp_Date::normal($r['replytime']):'-' ?><br />
			<?= ($r['rnicky']) ? $r['replynick']:'<a href="/space_home/?uid='.$r['replyer'].'">'.$r['replyname'].'</a>'; ?>
		</td>
	</tr>
	<?php endforeach; endif; ?>
</table>
<div class="pg"><?= $this->pagination ?></div>