<div class="yui-main">
	<div class="yui-b">
		<div class="mg5 section yui-g">
			<div class="yui-u first">
				<img class="vm mgr10" src="<?= Alp_Url::img('icon/mix/+.gif') ?>" /><b>发布求助帖</b>
			</div>
			<div class="yui-u txtr"><a href="javascript:history.back()">返回上一页</a></div>
		</div>
		<form id="help_form" method="post" onsubmit="return pub_help()">
		<table class="mgl10 table-dashed" width="97%">
			<tr>
				<td width="10%" class="txtr">类型：</td>
				<td class="a-span"><?= $this->render('pub/type.phtml'); ?></td>
			</tr>
			<tr>
				<td class="txtr">归类：</td>
				<td>
					<select name="sort" id="help_sorts">
						
					</select>
					<input id="help_sort" type="text" name="sortname" value="" />
					<input onclick="create_sort()" type="button" value="创建" class="btn" />
				</td>
			</tr>
			<tr>
				<td class="txtr">标题：</td>
				<td>
					<input type="hidden" name="type" value="<?= $this->pub ?>" />
					<input type="text" name="title" size="90" />
				</td>
			</tr>
			<tr>
				<td class="txtr">图片：</td>
				<td id="pic_upload">
				</td>
			</tr>
			<tr>
				<td class="txtr">内容：</td>
				<td><?= Cmd::fck('content',null,'300px','99%') ?></td>
			</tr>
			<tr>
				<td class="txtr">公开给：</td>
				<td><?= $this->render('pub/private.phtml') ?>
					<input type="hidden" name="nicky" value="0" />
					<label for="nicky"><input type="checkbox" name="nicky" id="nicky" value="1" />使用昵称发布</label>
					&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
					<input id="submit" type="submit" value="发布帖子" class="btn" />
					<input type="hidden" name="group" value="<?= $this->gp ?>" />
				</td>
			</tr>
		</table>
		</form>
		<iframe name="pic_frame" class="hide" src="/public/upload/pic"></iframe>
	</div>
</div>

<script type="text/javascript">
	function pub_help()
	{
		$('#submit').attr('disabled', true).val('正在发布帖子，请稍候...');
		$('#content').val(FCKeditorAPI.GetInstance("content").GetXHTML());
		$.getJSON(
			'/space_bar/pub/help',
			$('#help_form').serializeArray(),
			function(data)
			{
				if(data.result == 'success')
				window.location.href = '/space_bar/help/?tid='+data.tid;
				else 
				{
					alert(data.result);
					$('#submit').attr('disabled', false).val('发布帖子');
				}
			}
		);
		return false;
	}
	function create_sort()
	{
		var v = $('#help_sort').val();
		$('.btn[type=button]').attr('disabled', true).val('创建中...');
		$.post(
			'/space_bar/help/create_sort',
			{sortname:v},
			function(data)
			{
				if(data == 'success')
				{
					$('#help_sorts').load('/space_bar/help/sorts');
					$('.btn[type=button]').attr('disabled', false).val('创建成功');
				}
				else 
				{
					alert(data);
					$('.btn[type=button]').attr('disabled', false).val('创建');
				}
				
			}
		);
	}
	function insert_html(html){FCKeditorAPI.GetInstance("content").InsertHtml(html);upreload();}
	$('#pic_upload').load('/public/upload/form?for=pic');
	$('#help_sorts').load('/space_bar/help/sorts');
</script>