<div class="yui-main">
	<h2 class="section">关于杭州浙江大学校友会</h2>
	<div style="background:url(<?= Alp_Url::img('v1/doc/constitution.jpg') ?>) no-repeat center; height:750px;"></div>
	<ul style="margin-left:120px;">
		<li class="pd5 f14"><a target="_blank" href="http://www.zjuhz.com/info/view/detail/id/189">杭州浙江大学校友会章程</a></li>
		<li class="pd5 f14"><a target="_blank" href="http://www.zjuhz.com/info/view/detail/id/190">杭州浙江大学校友会组织条例</a></li>
		<li class="pd5 f14"><a target="_blank" href="http://www.zjuhz.com/info/view/detail/id/192">杭州浙江大学校友会校友互助公约</a></li>
		<li class="pd5 f14"><a target="_blank" href="http://www.zjuhz.com/info/view/detail/id/191">杭州浙江大学校友会校友资料和运作信息管理条例</a></li>
		<li class="pd5 f14"><a target="_blank" href="http://www.zjuhz.com/info/view/detail/id/193">杭州浙大校友会组织架构及成员介绍</a></li>
	</ul>
	<div style="background:url(<?= Alp_Url::img('v1/doc/aboutus.jpg') ?>) no-repeat center; height:1094px;"></div>
</div>