<div class="yui-main">
	<div class="mg5 section yui-g">
		<div class="yui-u first f14" style="width:70%">
			<b>关于杭州浙江大学校友会</b>
		</div>
		<div class="yui-u txtr a-span" style="width:30%">
			<a href="javascript:history.back()">返回上一页</a>
		</div>
	</div>
	<h3 class="section-u">杭州校友会概述</h3>
	<p class="pd10">杭州浙江大学校友会（以下简称“杭州校友会”）是在校友总会的关心和指导下，由在杭州市的浙江大学校友自愿组成的、联合性、地方性、非营利性的社会组织。</p>
	<p class="pd10">杭州校友会的工作主要包括：</p>
	<p class="pd10">1）建立校友联络系统和机制；</p>
	<p class="pd10">2）打通母校、校友、企业通道；</p>
	<p class="pd10">3）组织各种活动，帮助校友，加深校友和母校的联系和感情；</p>
  <p class="pd10">4）建立各种专项的校友组群，实现有效的互助。杭州校友会遵循校友会章程和各项制度运作，建立校友联络系统和各种校友活动群体，组织各种校友活动。</p>
	<table width="800" border="0" cellspacing="0" cellpadding="0" align="center">
	  <tr>
	    <td bgcolor="#f3f3f3"><p class="pd10">&nbsp;</p>
          <ul class="pdl10">
            <li><b>宗旨：</b>联络校友、团结互助、爱校荣校、建设杭州</li>
            <li><b>目标：</b>建成杭州浙大校友间、校友与母校间沟通和互助的平台，扶持校友创业，为校友企业搭建合作平台。</li>
            <li><b>理念：</b>杭州校友会坚信”校友关系是人生中第二重要的社会关系”，这一理念始终推动我们的工作。</li>
            <li><b>工作方针：</b>以校友俱乐部为主角、校友网站为平台 </li>
          </ul>
        <p>&nbsp;</p></td>
      </tr>
  </table>
	<p class="pd10">&nbsp;
	</p>
	<p class="pd10">地址：杭州市西溪路525号浙大科技园C楼608室  （310013）<br />
	电话：0571-89988185 0571-89988186<br />
	邮箱：<a href="mailto:zjuhz@zju.edu.cn">zjuhz@zju.edu.cn</a> &nbsp;<a href="mailto:5izju@zjuhz.com">5izju@zjuhz.com</a><br />
	网站：<a href="http://www.zjuhz.com/">www.zjuhz.com</a>
	</p>
	<h3 class="section-u">杭州浙江大学校友会机构 </h3>
	<ul class="pdl10">
	<li><b>名誉会长：</b>张浚生</li>
	<li><b>顾问：</b>安志云　陈端　林正范　高法根　黄书孟　虞荣仁</li>
	<li><b>会长：</b>陈鸿</li>
	<li><b>副会长：</b>刘巍　郑家林　叶志前　吴晓农　孙旭东</li>
	<li><b>理事：</b><a href="http://www.zjuhz.com/space_bar/news/view?tid=2793">点击查看名单</a></li>
	<li><b>秘书处：</b><a href="http://www.zjuhz.com/space_bar/news/view?tid=2793">点击查看名单</a></li>
	<li><b>部门办公：</b><a href="http://www.zjuhz.com/space_bar/news/view?tid=2793">点击查看名单</a></li>
	</ul>
  <h3 class="section-u">杭州校友会制度</h3>
	<ul class="pdl10">
	<li><a href="http://www.zjuhz.com/space_bar/news/view?tid=2802">章程</a></li>
	<li><a href="http://www.zjuhz.com/space_bar/news/view?tid=2803">互助公约</a></li>
	<li><a href="http://www.zjuhz.com/space_bar/news/view?tid=2805">组织条例</a></li>
	<li><a href="http://www.zjuhz.com/space_bar/news/view?tid=2804">资料和运作信息管理条例</a></li>
	<li><a href="http://www.zjuhz.com/space_bar/news/view?tid=2806">热心度体系</a></li>
	</ul>
	<h3 class="section-u">杭州校友会大事记</h3>
	<ul>
	<li><a href="http://www.zjuhz.com/space_bar/news/view?tid=6216">杭州浙江大学校友会大事记(2007~2010)  </a></li>
	</ul>
</div>