<div class="yui-main">
	<div class="yui-b">
		<div class="mg5 section yui-g">
			<div class="yui-u first">
				<img class="vm mgr10" src="<?= Alp_Url::img('icon/mix/+.gif') ?>" /><b>发布图片帖</b>
			</div>
			<div class="yui-u txtr a-span">
				<a href="javascript:history.back()">返回上一页</a>
				<?php if($this->gp): ?>
					<a href="/space_group/home/?id=<?= $this->gp ?>">返回群组首页</a>
				<?php endif; ?>
			</div>
		</div>
		<form id="photo_form" method="post" onsubmit="return pub_photo()">
		<table class="mgl10 table-dashed" width="97%">
			<tr>
				<td width="10%" class="txtr">类型：</td>
				<td class="a-span"><?= $this->render('pub/type.phtml'); ?></td>
			</tr>
			<tr>
				<td class="txtr">标题：</td>
				<td>
					<input type="hidden" name="type" value="<?= $this->pub ?>" />
					<input type="text" name="title" size="90" />
				</td>
			</tr>
			<tr id="breakline">
				<td class="txtr">图片：</td>
				<td id="photo_upload"></td>
			</tr>
			<tr>
				<td class="txtr">公开给：</td>
				<td><?= $this->render('pub/private.phtml') ?>
					<?= $this->render('pub/nicky.phtml') ?>
					&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
					<input id="submit" type="submit" value="发布帖子" class="btn" />
					<input type="hidden" name="group" value="<?= $this->gp ?>" />
				</td>
			</tr>
		</table>
		</form>
		<iframe name="photo_frame" class="hide" src="/public/upload/photo"></iframe>
	</div>
</div>
<?= $this->render('sidebar.phtml'); ?>
<script type="text/javascript">
	function pub_photo()
	{
		$('#submit').attr('disabled', true).val('正在发布帖子，请稍候...');
		$.post(
			'/space_bar/pub/photo',
			$('#photo_form').serializeArray(),
			function(data)
			{
				if(data.result == 'success')
				window.location.href = '/space_bar/photo/view?tid='+data.tid;
				else 
				{
					alert(data.result);
					$('#submit').attr('disabled', false).val('发布帖子');
				}
			},
			'json'
		);
		return false;
	}
	function create_item(uid, file)
	{
		var x = $('.file_itme').length;
		$('#breakline').after('<tr class="file_itme" id="f'+x+'"><td class="txtc"><img src="/upload/photo/'+uid+'/'+file+'" width="150" /><input type="hidden" name="photos[]" value="'+file+'" /><br />[<a href="javascript:del_item('+x+',\''+file+'\')">删除</a>]</td><td><textarea name="intros[]" style="width:75%;height:120px"></textarea></td></tr>');
	}
	function del_item(x, file)
	{
		$.post('/public/upload/del_photo?file='+file,null,function(data){ 
			if(data=='success') $('#f'+x).fadeOut(500, function(){ $(this).empty(); });
		});
	}
	$('#photo_upload').load('/public/upload/form?for=photo');
</script>