<select name="private">
	<?php if(!$this->gp): ?>
	<option value="0">仅自己</option>
	<option value="1">仅好友</option>
	<option value="3" selected="selected">仅校友</option>
	<option value="4">所有人</option>
	<?php else: ?>
	<option value="0">仅自己</option>
	<option value="1">仅好友</option>
	<option value="2">仅群组成员</option>
	<option value="3" selected="selected">仅校友</option>
	<option value="4">所有人</option>
	<?php endif; ?>
</select>