<?php 
	$gp = ''; 
	if($this->gp):
	$gp = '&gp='.$this->gp;
?>
<div class="quiet pd5">
	<img src="<?= Alp_Url::img('icon/1616/att_s.gif'); ?>" />
	当前为群组发帖，发布后只会显示在xxxx群组首页中。
</div>
<?php endif; ?>
<a href="?pub=topic<?= $gp ?>" style="<?= ($this->pub == 'topic')?'color:#333;text-decoration:underline':''; ?>">
	<img src="<?= Alp_Url::img('icon/1616/talk.gif'); ?>" /> 话题帖
</a>
<a href="?pub=news<?= $gp ?>" style="<?= ($this->pub == 'news')?'color:#333;text-decoration:underline':''; ?>">
	<img src="<?= Alp_Url::img('icon/1616/news.gif'); ?>" /> 新闻帖
</a>