<div class="yui-main">
	<div class="yui-b">
		<div class="mg5 section yui-g">
			<div class="yui-u first">
				<img class="vm mgr10" src="<?= Alp_Url::img('icon/mix/+.gif') ?>" /><b>发布投票帖</b>
			</div>
			<div class="yui-u txtr a-span">
				<a href="javascript:history.back()">返回上一页</a>
				<?php if($this->gp): ?>
					<a href="/space_group/home/?id=<?= $this->gp ?>">返回群组首页</a>
				<?php endif; ?>
			</div>
		</div>
		<form id="vote_form" method="post" onsubmit="return pub_vote()">
		<table class="mgl10 table-dashed" width="97%">
			<tr>
				<td width="10%" class="txtr">类型：</td>
				<td class="a-span"><?= $this->render('pub/type.phtml'); ?></td>
			</tr>
			<tr>
				<td class="txtr">主题：</td>
				<td>
					<input type="hidden" name="type" value="<?= $this->pub ?>" />
					<input type="text" name="title" size="90" />
				</td>
			</tr>
			<tr>
				<td class="txtr">选项：</td>
				<td class="quiet">
					刷新页面选项会变为初始数目，在提交投票前最好不要刷新页面
				</td>
			</tr>
			<tr class="option_item">
				<td class="txtr">1：</td>
				<td><input name="options[]" type="text" size="90" /></td>
			</tr>
			<tr class="option_item">
				<td class="txtr">2：</td>
				<td><input name="options[]" type="text" size="90" /></td>
			</tr>
			<tr class="option_item">
				<td class="txtr">3：</td>
				<td><input name="options[]" type="text" size="90" /></td>
			</tr>
			<tr class="option_item">
				<td class="txtr">4：</td>
				<td><input name="options[]" type="text" size="90" /></td>
			</tr>
			<tr class="option_item">
				<td class="txtr">5：</td>
				<td><input name="options[]" type="text" size="90" /></td>
			</tr>
			<tr>
				<td></td>
				<td><a href="javascript:add_option()">+ 增加选项</a></td>
			</tr>
			<tr>
				<td class="txtr">可选：</td>
				<td>
					<select name="maxselect" id="maxselect">
						<option value="1">1项</option>
						<option value="2">2项</option>
						<option value="3">3项</option>
						<option value="4">4项</option>
					</select>
				</td>
			</tr>
			<tr>
				<td class="txtr">图片：</td>
				<td id="pic_upload">
				</td>
			</tr>
			<tr>
				<td class="txtr">说明：</td>
				<td><?= Cmd::fck('memo',null,'200px','99%') ?></td>
			</tr>
			<tr>
				<td class="txtr">公开给：</td>
				<td><?= $this->render('pub/private.phtml') ?>
					<?= $this->render('pub/nicky.phtml') ?>
					&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
					<input id="submit" type="submit" value="发布帖子" class="btn" />
					<input type="hidden" name="group" value="<?= $this->gp ?>" />
				</td>
			</tr>
		</table>
		</form>
		<iframe name="pic_frame" class="hide" src="/public/upload/pic"></iframe>
	</div>
</div>
<?= $this->render('sidebar.phtml'); ?>
<script type="text/javascript">
	function pub_vote()
	{
		$('#submit').attr('disabled', true).val('正在发布帖子，请稍候...');
		$('#memo').val(FCKeditorAPI.GetInstance("memo").GetXHTML());
		$.post(
			'/space_bar/pub/vote',
			$('#vote_form').serializeArray(),
			function(data)
			{
				if(data.result == 'success')
				window.location.href = '/space_bar/vote/view?tid='+data.tid;
				else 
				{
					alert(data.result);
					$('#submit').attr('disabled', false).val('发布帖子');
				}
			},
			'json'
		);
		return false;
	}
	function insert_html(html){FCKeditorAPI.GetInstance("memo").InsertHtml(html);upreload();}
	function add_option()
	{
		var x = $('.option_item').length;
		$('.option_item:last').after('<tr class="option_item"><td class="txtr">'+(x+1)+'：</td><td><input name="options[]" type="text" size="90" /></td></tr>');
		$('#maxselect').append('<option value="'+(x)+'">'+(x)+'项</option>');
	}
	$('#pic_upload').load('/public/upload/form?for=pic');
</script>