<?php 
	$flag = $_COOKIE['dynameic_adduser'] == null ? 1:$_COOKIE['dynameic_adduser']; 
	$str = '';
?>
<tr class="bcolor-z quiet">
	<td>
		<img src="<?= Alp_Url::img('icon/log/add_user.gif') ?>" /> 
		校友注册信息
	</td>
	<td class="txtr" width="80">
		<a id="adduser_tab" href="javascript:htab(<?= $flag ?>,'adduser')">
		<?= $flag == 1 ? '-折起':'+展开' ?>
		</a>
	</td>
</tr>
<?php 
	foreach ($this->log as $log)
	{
		if($log['key'] == 'add_user')
		{
			$str .= '<a href="/space_home/?uid='.$log['uid'].'">'.$log['uname'].'</a>
					<span class="f9">['.date('Y-m-d H:i', $log['time']).']</span>
					&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;';
		}
	}
	if($str != ''):
?>
<tr class="dynameic_adduser">
	<td class="quiet"><?= $str.$this->event['add_user'] ?></td>
</tr>
<?php else: ?>
<tr class="dynameic_adduser">
	<td class="quiet">没有相关信息...</td>
</tr>
<?php endif; if($flag == 0) : ?>
<script>
	$('.dynameic_adduser').hide();
</script>
<?php endif; ?>