<?php 
	$flag = $_COOKIE['dynameic_replybar'] == null ? 1:$_COOKIE['dynameic_replybar']; 
	$str = '';
?>
<tr class="bcolor-z quiet">
	<td>
		<img src="<?= Alp_Url::img('icon/1616/topic.gif') ?>" /> 
		回复信息
	</td>
	<td class="txtr" width="80">
		<a id="replybar_tab" href="javascript:htab(<?= $flag ?>,'replybar')">
		<?= $flag == 1 ? '-折起':'+展开' ?>
		</a>
	</td>
</tr>

<?php 
	$tid_box = array();
	foreach ($this->log as $log)
	{
		if($log['tid'] && $log['key'] == 'add_reply')
		{
			$tid_box[$log['tid']][] = $log;
		}
	}
?>

<?php if(count($tid_box) > 0): foreach ($tid_box as $tid => $logs): ?>
<tr class="dynameic_replybar">
	<td class="quiet">
		<a class="f14" href="/space_bar/<?= $logs[0]['type'] ?>/view?id=<?= $tid ?>"><?= $logs[0]['title'] ?></a>
		<hr />
		<?php foreach ($logs as $v): ?>
		<a href="/space_home/?uid=<?= $v['uid'] ?>"><?= $v['uname'] ?></a> 
		<span class="quiet f9"><?= date('Y-m-d H:i', $v['time']) ?></span>
		<div class="pd5"><?= stripslashes($v['value']) ?></div>
		<?php endforeach; ?>
	</td>
</tr>
<?php endforeach; else: ?>
<tr class="dynameic_replybar">
	<td class="quiet">没有相关信息...</td>
</tr>
<?php endif; ?>



<?php if($flag == 0) : ?>
<script>
	$('.dynameic_addbar').hide();
</script>
<?php endif; ?>