<?php if($this->comments): ?>
	<div class="pg"><?= $this->pagination ?></div>
<?php foreach ($this->comments as $i => $r): ?>
<table width="100%">
  <tr>
    <td rowspan="2" width="10%" valign="top">
    	<div class="head40 txtc">
			<?php if($r['nicky']): ?>
				<img class="mg10" src="<?= Cmd::userhead(0,40,Cmd::getSess('profile','sex')) ?>" />
			<?php else: ?>
			<a href="/space_home/?uid=<?= $r['uid'] ?>">
				<img class="mg10" src="<?= Cmd::userhead($r['uid']) ?>" />
			</a>
			<?php endif; ?>
		</div>
    </td>
    <td class="yui-g section-sub quiet" width="90%">
    	<div class="yui-u first" style="width:80%">
			<?php if($r['nicky']): ?>
			<?= $r['unick'] ?>
			<?php else: ?>
			<a href="/space_home/?uid=<?= $r['uid'] ?>"><?= $r['uname'] ?></a>
			<?php endif; ?>说道：
		</div>
		<div class="yui-u txtr" style="width:20%">
			<?= date('y-m-d H:i:s', $r['time']) ?>
			&nbsp;&nbsp;&nbsp;&nbsp;
			<?= ($i+2)+($this->offset) ?>楼
		</div>
    </td>
  </tr>
  <tr>
  	<td>
  		<div style="line-height:150%;">
			<?= stripslashes($r['content']); ?>
		</div>
  	</td>
  </tr>
</table>
<?php endforeach; ?>
	<div class="pg"><?= $this->pagination ?></div>
<?php endif; ?>
