<hr />
<div id="comment_box"></div>
<hr />
<?= $this->render('comment/form.phtml'); ?>
<script type="text/javascript">
	function load_comment(p)
	{
		$('#comment_box').fadeTo(100, '0.5');
		$('#comment_box').load(
		'/space_bar/comment/list?tid=<?= $this->row['tid'] ?>&p='+p+'#comment_box', 
		function(){ $('#comment_box').fadeTo(100,'1'); });	
	}
	$('#comment_box').html('<div class="txtc"><img src="<?= Alp_Url::img('icon/loading/v2.gif') ?>" /></div>');
	$('#comment_box').load('/space_bar/comment/list?tid=<?= $this->row['tid'] ?>&p=<?= $this->page ?>');	
</script>