<div class="yui-g">
	<div class="yui-u first">
		<div class="mglr10 tb-box">
			<a href="/space_search/?for=user" <?= ($this->for == 'user')?'class="tb-on"':'class="tb-of"' ?>>校友</a><span class="tb-rbg"></span>
			<a href="/space_search/?for=bar" <?= ($this->for == 'bar')?'class="tb-on"':'class="tb-of"' ?>>帖子</a><span class="tb-rbg"></span>
			<a href="/space_search/?for=group" <?= ($this->for == 'group')?'class="tb-on"':'class="tb-of"' ?>>群组</a><span class="tb-rbg"></span>
		</div>
	</div>
	<div class="yui-u txtr">
		<form method="get">
			<input type="hidden" name="for" value="<?= $this->for ?>" />
			<?php if($this->for == 'bar'): ?>
			<input type="hidden" name="range" value="<?= $this->range ?>" />
			<?php endif; ?>
			<input type="text" name="key" value="<?= $this->key ?>" />
			<input class="btn" type="submit" value="查找" />
		</form>
	</div>
</div>

