<div id="hd">
	<table>
		<tr>
			<td width="220"><img src="<?= Logic_Addon_Partners::logo($this->corp['cid']) ?>" /></td>
			<td class="f28 bold"><?= $this->corp['name'] ?></td>
		</tr>
		<tr>
			<td colspan="2"><img src="<?= Logic_Addon_Partners::banner($this->corp['cid'])?>" /></td>
		</tr>
	</table>
</div>
<div id="bd">
	<div id="yui-main">
		<div class="yui-b">
			<div class="mgl10">
				<?= stripslashes($this->corp['intro']) ?>
			</div>
		</div>
	</div>
	<div class="yui-b">
		<table width="100%" style="border-left:1px dashed #ccc">
			<?php if($this->manager): ?>
			<tr>
				<td class="f14 section">
				<a href="/addon_partners/manage/corplist?uid=<?= $this->corp['uid'] ?>">返回企业列表</a>
				</td>
			</tr>
			<?php endif; ?>
			<tr>
				<td class="f14"><img class="vm" src="<?= Alp_Url::img('icon/clean/talk.gif'); ?>" /> 
				联系人：<?= $this->corp['contact'] ?></td>
			</tr>
			<tr>
				<td class="f14"><img class="vm" src="<?= Alp_Url::img('icon/clean/tel.gif'); ?>" /> 
				<?= $this->corp['tel'] ?></td>
			</tr>
			<tr>
				<td class="f14"><img class="vm" src="<?= Alp_Url::img('icon/clean/position.gif'); ?>" /> 
				<?= $this->corp['address'] ?></td>
			</tr>
			<tr>
				<td class="f14"><img class="vm" src="<?= Alp_Url::img('icon/clean/home.gif'); ?>" /> 
				<a href="<?= $this->corp['website'] ?>" target="_blank"><?= $this->corp['website'] ?></a></td>
			</tr>
		</table>
	</div>
</div>

<script>
	$('#doc2').addClass('yui-t5');
</script>