<p class="a-span pd10" style="border-bottom:1px dashed #ccc; font-size:13px;">
	<a href="base" <?= ($this->tab == 'base')?'style="color:#333;text-decoration:underline"':'' ?>>基本资料</a>
	<a href="contact" <?= ($this->tab == 'contact')?'style="color:#333;text-decoration:underline"':'' ?>>联系方式</a> 
	<a href="intro" <?= ($this->tab == 'intro')?'style="color:#333;text-decoration:underline"':'' ?>>个人介绍</a> 
	<a href="edu" <?= ($this->tab == 'edu')?'style="color:#333;text-decoration:underline"':'' ?>>教育情况</a>
	<a href="career" <?= ($this->tab == 'career')?'style="color:#333;text-decoration:underline"':'' ?>>工作情况</a>
	<a href="head" <?= ($this->tab == 'head')?'style="color:#333;text-decoration:underline"':'' ?>>头像照片</a>
	<a href="qmd" <?= ($this->tab == 'qmd')?'style="color:#333;text-decoration:underline"':'' ?>>签名档</a>
</p>