<div class="yui-g">
	<div class="yui-u first" style="width:75%">
		<div class="tb-box">
			<a href="/space_group/manage/?id=<?= $this->gid ?>&type=basic" <?= ($this->type == 'basic')?'class="tb-on"':'class="tb-of"' ?>>基本信息</a><span class="tb-rbg"></span>
			<a href="/space_group/manage/?id=<?= $this->gid ?>&type=logo" <?= ($this->type == 'logo')?'class="tb-on"':'class="tb-of"' ?>>群LOGO</a><span class="tb-rbg"></span>
			<a href="/space_group/manage/?id=<?= $this->gid ?>&type=msg" <?= ($this->type == 'msg')?'class="tb-on"':'class="tb-of"' ?>>发群消息</a><span class="tb-rbg"></span>
			<a href="/space_group/manage/?id=<?= $this->gid ?>&type=member" <?= ($this->type == 'member')?'class="tb-on"':'class="tb-of"' ?>>成员管理</a><span class="tb-rbg"></span>
			<a href="/space_group/manage/?id=<?= $this->gid ?>&type=bar" <?= ($this->type == 'bar')?'class="tb-on"':'class="tb-of"' ?>>帖子管理</a><span class="tb-rbg"></span>
		</div>
	</div>
	<div class="yui-u txtr a-span" style="width:25%">

	</div>
</div>