<div class="yui-main">
	<div class="yui-b">
		<div class="mg5 section yui-g">
			<div class="yui-u first">
				<img class="vm mgr10" src="<?= Alp_Url::img('icon/mix/+.gif') ?>" /><b>创建群组俱乐部 - 第二步</b>
			</div>
			<div class="yui-u txtr a-span">
				<a href="javascript:history.back()">返回上一页</a>
			</div>
		</div>
		<div class="pdlr10">
			<h3>填写群组俱乐部必要信息：</h3>
			<form id="group_form" method="post" onsubmit="return pub_group()">
				<table class="table-dashed">
					<tr>
						<td>群名称：</td>
						<td><input type="text" name="name" size="30" /></td>
					</tr>
					<tr>
						<td valign="top">群介绍：</td>
						<td><textarea name="intro" style="width:300px;height:120px;"></textarea></td>
					</tr>
					<tr>
						<td></td>
						<td><input class="btn" type="submit" value="确定" /></td>
					</tr>
				</table>
			</form>
		</div>
	</div>
</div>

<script type="text/javascript">
	function pub_group()
	{
		$('input:submit').val('创建中...').attr('disabled', true);
		$.post('/space_group/pub/create?type=<?= $this->type ?>', $('#group_form').serializeArray(), function(data){
			if(data.result == 'success')
			location.href = '/space_group/home/?id='+data.gid;
			else { alert(data.result); $('input:submit').val('确定').attr('disabled', false); }
		},'json');
		return false;
	}
</script>

<?= $this->render('sidebar.phtml'); ?>