<div class="yui-main">
	<div class="yui-b">
		<div class="mg5 section yui-g">
			<div class="yui-u first" style="width:80%">
				<img class="vm mgr10" src="<?= Alp_Url::img('icon/1616/vote.gif') ?>" /><b>投票调查</b>
			</div>
			<div class="yui-u txtr" style="width:20%"><a href="javascript:history.back()">返回上一页</a></div>
		</div>
		<?= $this->render('tab.phtml'); ?>
		<table width="100%" class="mgt10 table-dashed">
			<?php if(count($this->rows) > 0): foreach ($this->rows as $i => $r): ?>
			<tr>
				<td class="txtc" width="10%">
					<img src="<?= Alp_Url::img('icon/classic/vote.gif'); ?>" />
				</td>
				<td <?= ($i%2 == 1) ? 'bgcolor="#f5f5f5"' : '' ?> style="line-height:150%">
					<?= ($r['nicky']) ? $r['pubnick'] : '<a href="/space_home/?uid='.$r['puber'].'">'.$r['pubname'].'</a>'; ?>
					<img src="<?= Alp_Url::img('icon/mix/quote2.gif'); ?>" />
					<a href="/space_bar/vote/view?tid=<?= $r['tid'] ?>" class="f14"><?= stripcslashes($r['title']) ?></a>
					<?= Logic_Space_Bar::subpage($r); ?>
					<br />
					<span class="quiet">
						<span class="tp5"><?= Alp_Date::normal($r['pubtime']); ?></span>
						&nbsp;&nbsp;
						查看<span class="f9">(<?= $r['click'] ?>)</span>
						&nbsp;&nbsp;
						回复<span class="f9">(<?= $r['reply'] ?>)</span>
						&nbsp;&nbsp;
						顶<span class="f9">(<?= $r['rate'] ?>)</span>
						&nbsp;&nbsp;
						投票数<span class="f9">(<?= $r['votenum'] ?>)</span>
					</span>
				</td>
			</tr>
			<?php endforeach; else: ?>
			<tr>
				<td><img class="vm" src="<?= Alp_Url::img('icon/1616/att.gif'); ?>" /> 没有找到任何相关的帖子</td>
			</tr>
			<?php endif; ?>
		</table>
		<div class="pg"><?= $this->pagination ?></div>
	</div>
</div>