<div class="mglr10 tb-box">
	<a href="/space_search/?for=user" <?= ($this->for == 'user')?'class="tb-on"':'class="tb-of"' ?>>校友</a><span class="tb-rbg"></span>
	<a href="/space_search/?for=bar" <?= ($this->for == 'bar')?'class="tb-on"':'class="tb-of"' ?>>帖子</a><span class="tb-rbg"></span>
	<a href="/space_search/?for=group" <?= ($this->for == 'group')?'class="tb-on"':'class="tb-of"' ?>>群组</a><span class="tb-rbg"></span>
</div>