<div class="yui-main">
	<div class="mg5 section yui-g">
		<div class="yui-u first f14" style="width:70%">
			<b>网站功能帮助视频</b>
		</div>
		<div class="yui-u txtr a-span" style="width:30%">
			<a href="javascript:history.back()">返回上一页</a>
		</div>
	</div>
        <h3 class="section-u">如何一次性上传大量图片？</h3>
        <p class="pd10">查看视频教程：<a href="/upload/help/photo.htm" rel="facebox">如何上传图片</a></p>
        
        <h3 class="section-u">如何发起活动？</h3>
        <p class="pd10">查看视频教程：<a href="/upload/help/act.htm" rel="facebox">如何发起活动</a></p>
        <p class="pd10 quiet">更多视频教程制作中..</p>
        <h3 class="section-u">使用疑问在线解答</h3>
        <p class="pd10"><a href=" http://sighttp.qq.com/cgi-bin/check?sigkey=331440b66376f0810e35f3b268b5a3ff0f4996ca528110e1e28027d08c78cd0de62a3f6aba04f7bfd32678e6127ad2ac5031198d65df5dbb"; target=_blank; onclick="var tempSrc=' http://sighttp.qq.com/wpa.js?rantime='+Math.random()+'&sigkey=331440b66376f0810e35f3b268b5a3ff0f4996ca528110e1e28027d08c78cd0de62a3f6aba04f7bfd32678e6127ad2ac5031198d65df5dbb';var oldscript=document.getElementById('testJs');var newscript=document.createElement('script');newscript.setAttribute('type','text/javascript'); newscript.setAttribute('id', 'testJs');newscript.setAttribute('src',tempSrc);if(oldscript == null){document.body.appendChild(newscript);}else{oldscript.parentNode.replaceChild(newscript, oldscript);}return false;"><img border="0" SRC=' http://wpa.qq.com/pa?p=1:516567773:3' alt="网站使用帮助在线咨询"></a></p>
</div>

<script>$('a[rel="facebox"]').facebox();</script>