<div class="yui-main">
	<div class="mg5 section yui-g">
		<div class="yui-u first f14" style="width:70%">
			<b>网站功能帮助视频</b>
		</div>
		<div class="yui-u txtr a-span" style="width:30%">
			<a href="javascript:history.back()">返回上一页</a>
		</div>
	</div>
        <h3 class="section-u">如何一次性上传大量图片？</h3>
        <p class="pd10">查看视频教程：<a href="/upload/help/photo.htm" rel="facebox">如何上传图片</a></p>
        <p class="pd10 quiet">更多视频教程制作中..</p>
        <h3 class="section-u">使用疑问在线解答</h3>
        <p class="pd10"></p>
</div>

<script>$('a[rel="facebox"]').facebox();</script>