<div class="mglr10 yui-g a-span">
	<div class="yui-u first" style="width:60%">
		<a href="?type=<?= $this->type ?>&order=time" style="<?= ($this->order == 'time')?'color:#333;text-decoration:underline':''; ?>">发布时间</a>
		<a href="?type=<?= $this->type ?>&order=reply" style="<?= ($this->order == 'reply')?'color:#333;text-decoration:underline':''; ?>">回复数量</a>
		<a href="?type=<?= $this->type ?>&order=click" style="<?= ($this->order == 'click')?'color:#333;text-decoration:underline':''; ?>">查看次数</a>
		<a href="">我发布的</a>
		<a href="">我参与的</a>
	</div>
	<div class="yui-u txtr" style="width:40%">
		<a href="/space_bar/?pub=<?= $this->type ?>">
			<img class="vm" src="<?= Alp_Url::img('icon/mix/+.gif') ?>" /> 发布新帖</a>
		<a href="">
			<img class="vm" src="<?= Alp_Url::img('icon/mix/search.gif') ?>" /> 帖子搜索</a>
	</div>
</div>