<div class="txtr a-span">
	<a href="javascript:load_rate(<?= $this->row['rate'] ?>)">
		<img id="rate_icon" src="<?= Alp_Url::img('icon/mix/ding.gif'); ?>" />
		顶(<span id="rate_box"><?= $this->row['rate'] ?></span>)
	</a>
	<?php if(Logic_Space_Bar::isFav($this->row, Cmd::uid())): ?>
	<a href="javascript:load_fav('off')"><img id="fav_icon" src="<?= Alp_Url::img('icon/mix/fav.gif'); ?>" />收藏</a>
	<?php else: ?>
	<a href="javascript:load_fav('on')"><img id="fav_icon" src="<?= Alp_Url::img('icon/mix/fav_off.gif'); ?>" />收藏</a>
	<?php endif; ?>
</div>
<script type="text/javascript">
	function load_rate(v)
	{
		$.post(
			'/space_bar/toolbar/rate?tid=<?= $this->row['tid'] ?>',
			function(data)
			{ 
				if(data == 'success') 
				{
					$('#rate_icon').fadeOut(500,function(){ $(this).fadeIn(500) });
					$('#rate_box').html(v+1);
				}
				else alert('不能连续顶帖哦');
			}
		);
	}
	function load_fav(v)
	{
		$.post(
			'/space_bar/toolbar/fav?tid=<?= $this->row['tid'] ?>&type=<?= $this->row['type'] ?>',
			function(data)
			{
				if(data == 'on')
				$('#fav_icon').attr('src', '<?= Alp_Url::img('icon/mix/fav.gif'); ?>');
				else if(data == 'off')
				$('#fav_icon').attr('src', '<?= Alp_Url::img('icon/mix/fav_off.gif'); ?>');
				else
				alert(data);
			}
		);
	}
</script>