<div class="mglr10 yui-g a-span">
	<div class="yui-u first" style="width:75%">
	<form method="get" id="tab_form">
	筛选：
		<?= ($this->type == 'help') ? $this->action('sortlist', 'help', 'space_bar'):'' ?>
		<?= ($this->type == 'events') ? $this->action('sortlist', 'events', 'space_bar'):'' ?>
		<?= ($this->type == 'news') ? $this->action('sortlist', 'news', 'space_bar'):'' ?>
		<select name="where" onchange="$('#tab_form').submit();">
			<option value="all" <?= ($this->where == 'all') ? 'selected="selected"':'' ?>>所有的</option>
			<option value="pub" <?= ($this->where == 'pub') ? 'selected="selected"':'' ?>>我发布的</option>
			<option value="join" <?= ($this->where == 'join') ? 'selected="selected"':'' ?>>我参与的</option>
			<option value="fav" <?= ($this->where == 'fav') ? 'selected="selected"':'' ?>>我收藏的</option>
		</select>
		<select name="order" onchange="$('#tab_form').submit();">
            <option value="rtime" <?= ($this->order == 'rtime') ? 'selected="selected"':'' ?>>新回复</option>
			<option value="time" <?= ($this->order == 'time') ? 'selected="selected"':'' ?>>新发布</option>
			<option value="reply" <?= ($this->order == 'reply') ? 'selected="selected"':'' ?>>回复数</option>
			<option value="click" <?= ($this->order == 'click') ? 'selected="selected"':'' ?>>查看数</option>
			<option value="rate" <?= ($this->order == 'rate') ? 'selected="selected"':'' ?>>被顶数</option>
		</select>
		<input type="hidden" name="type" value="<?= $this->type ?>" />
	</form>
	</div>
	<div class="yui-u txtr" style="width:25%">
		<a href="/space_bar/?pub=<?= $this->type ?>">
			<img class="vm" src="<?= Alp_Url::img('icon/mix/+.gif') ?>" /> 发布</a>
		<a href="/space_search/?for=bar&range=<?= $this->type ?>">
			<img class="vm" src="<?= Alp_Url::img('icon/mix/search.gif') ?>" /> 搜索</a>
	</div>
</div>