<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <?= $this->headTitle('杭州浙江大学校友会_zjuhz.com')->setSeparator('_'); ?>
    <script type="text/javascript" src="/js/common.js"></script>
    <?= $this->headScript() ?>
    <link rel="stylesheet" type="text/css" href="/cs/v1.css" />
    <?= $this->headLink() ?>
</head>
<body>
<div class="yui-d2f">
    <div id="hd" class="yui-g" style="height:70px;">
    	<div class="yui-u first">
    		<div class="pd10">
            <img class="vm" src="<?= Alp_Url::img('icon/cartoon/tool.gif'); ?>" /><b>zjuhz.com 附加组件控制台</b>
            </div>
        </div>
        <div class="yui-u hd-r"></div>
    </div>
    <div id="bd">
    <?= $this->layout()->content ?>
    </div>
    
    	<div id="ft-l"></div>
		<div id="ft-r"></div>
</div>
</body>

<script type="text/javascript">
	$('#mod_<?= $this->mod_name ?>').css({'font-weight':'bold', 'text-decoration':'underline'});
</script>
</html>
