<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <?= $this->headTitle('杭州浙江大学校友会_zjuhz.com')->setSeparator('_'); ?>
    <script type="text/javascript" src="/js/common.js"></script>
    <?= $this->headScript() ?>
    <link rel="stylesheet" type="text/css" href="/cs/v1.css" />
    <?= $this->headLink() ?>
</head>
<body>
<div class="yui-d3f">
    <div id="hd" class="yui-g">
        <div class="yui-u first" style="width:200px">
            <a href="/"><img src="/im/v1/logo.gif" /></a>
        </div>
        <div class="yui-u hd-r" style="width:580px">
            <?= $this->partial('topnav.phtml') ?>
        </div>
    </div>
    <div id="bd">
    <?= $this->layout()->content ?>
    </div>

		<div id="ft-l"></div>
		<div id="ft-r"></div>

    <div id="ft">
        <?= $this->partial('footer.phtml') ?>
    </div>
</div>

<script type="text/javascript">
	function check_msgbox()
	{
		$.getJSON('/api_json/msg/check',function(data){
			if(parseInt(data.result) > 0){ $('#msgstate').attr('src', '<?= Alp_Url::img('icon/1616/newmail.gif') ?>'); }
			else $('#msgstate').attr('src', '<?= Alp_Url::img('icon/1616/mail.gif') ?>');
			$('#json_msgbox').text(data.result);
		});
	}
	check_msgbox();
	var msgbox = window.setInterval("check_msgbox()", 5000);
</script>

</body>
</html>
