<div class="yui-g">
	<div class="yui-u first" style="width:20%;">
		<div class="head80">
			<img style="margin:20px 0 0 20px" src="<?= Cmd::userhead($this->uid, '80', $this->profile['sex']) ?>" />
		</div>
		<div class="a-span" style="line-height:150%">
			<a href="/space_set/detail/?uid=<?= $this->uid ?>">详细资料</a>
			<a href="javascript:friend_add(<?= $this->uid ?>)">加为好友</a>
			<br />
			<a href="/space_msg/pm/?uid=<?= $this->uid ?>">发送信息</a>
		</div>
		<br /><br />
	</div>
	<div class="yui-u mgt10" style="width:79%;">
		<b class="f14"><?= $this->profile['username'] ?></b>
		<span class="quiet mgl10">
			<span id="iamdoing"></span>
		</span>
		<hr />
		<table class="table-dashed" width="100%">
		<?php foreach($this->home as $v): 
		$str = Logic_Space_Home::info($v, $this->uid) ?>
		<?php if($str): ?>
		<?php if($v == 'intro'): ?>
		<tr>
			<td class="txtr"><b>个人介绍：</b></td>
			<td><a id="intro_slide" href="javascript:slide('intro')">展开</a></td>
		</tr>
		<?php endif; ?>
		<?php if($v == 'contact'): ?>
		<tr>
			<td class="txtr"><b>联系方式：</b></td>
			<td><a id="contact_slide" href="javascript:slide('contact')">展开</a></td>
		</tr>
		<?php endif; ?>
		<?php if($v == 'career'): ?>
		<tr>
			<td class="txtr"><b>工作情况：</b></td>
			<td><a id="career_slide" href="javascript:slide('career')">展开</a></td>
		</tr>
		<?php endif; ?>
		<?= $str ?>
		<?php endif; endforeach; ?>
		</table>
	</div>
</div>

<script type="text/javascript">
	function getdoing()
	{
		$.get(
			'/space_home/index/getdoing?uid=<?= $this->uid ?>',
			null,
			function(data)
			{ 
				$('#iamdoing').text(data);
				$('#ing_put').val(data); 
			}
		);
	}
	function slide(p)
	{
		if($('#'+p+'_slide').text() == '展开'){
			$('.'+p).show(); $('#'+p+'_slide').text('折起');
		} else {
			$('.'+p).hide(); $('#'+p+'_slide').text('展开');
		}
	}
	getdoing();
</script>