<table class="table-dashed" width="100%">
<tr class="quiet bold section-sub">
	<td>操作人</td>
	<td>归类</td>
	<td>物资名称</td>
	<td>数额</td>
	<td>收支</td>
	<td class="txtc">时间</td>
</tr>
<?php if(count($this->rows) > 0): foreach ($this->rows as $r): ?>
<tr class="hover">
	<td><a href="/space_home/?uid=<?php echo $r['uid'] ?>"><?php echo $r['username']?></a></td>
	<td>
<a href="/space_group/bill/?id=<?php echo $r['gid'] ?>&sort=<?php echo urlencode($r['sort'])?>">	
<?php echo $r['sort']?></a></td>
	<td><?php echo $r['item']?></td>
	<td><?php echo $r['num']?></td>
	<td><?php echo $r['inout']=='in'?'收入':'支出' ?></td>
	<td class="quiet txtc f9">
		<?php echo date('y-m-d H:i', $r['time']) ?>
		<textarea class="hide"><?php echo $r['memo'] ?></textarea>
	</td>
</tr>
<?php endforeach; else: ?>
<tr><td colspan="5" class="quiet">暂无数据</td></tr>
<?php endif; ?>
</table>
<div class="pg"><?php echo $this->pagination ?></div>
<script type="text/javascript">
	$('.hover').mouseover(function(e){$(this).css('background','#ffc')});
	$('.hover').mouseout(function(e){$(this).css('background','#fff')});
	$('.hover').click(function(e){$('.bill_memo').remove(); var h = $(this).find('.hide').html(); 
	$(this).after('<tr class="bill_memo section-sub"><td colspan="6" class="quiet">备注：'+h+'</td></tr>'); })
</script>